// Code generated by go-swagger; DO NOT EDIT.

package nodepool_resource_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/warroyo/tmc-go-rest-sdk/models"
)

// NodepoolResourceServicePatchReader is a Reader for the NodepoolResourceServicePatch structure.
type NodepoolResourceServicePatchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NodepoolResourceServicePatchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNodepoolResourceServicePatchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewNodepoolResourceServicePatchDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewNodepoolResourceServicePatchOK creates a NodepoolResourceServicePatchOK with default headers values
func NewNodepoolResourceServicePatchOK() *NodepoolResourceServicePatchOK {
	return &NodepoolResourceServicePatchOK{}
}

/*
NodepoolResourceServicePatchOK describes a response with status code 200, with default header values.

A successful response.
*/
type NodepoolResourceServicePatchOK struct {
	Payload *models.ManagementclusterProvisionerTanzukubernetesclusterNodepoolPatchNodepoolResponse
}

// IsSuccess returns true when this nodepool resource service patch o k response has a 2xx status code
func (o *NodepoolResourceServicePatchOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this nodepool resource service patch o k response has a 3xx status code
func (o *NodepoolResourceServicePatchOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this nodepool resource service patch o k response has a 4xx status code
func (o *NodepoolResourceServicePatchOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this nodepool resource service patch o k response has a 5xx status code
func (o *NodepoolResourceServicePatchOK) IsServerError() bool {
	return false
}

// IsCode returns true when this nodepool resource service patch o k response a status code equal to that given
func (o *NodepoolResourceServicePatchOK) IsCode(code int) bool {
	return code == 200
}

func (o *NodepoolResourceServicePatchOK) Error() string {
	return fmt.Sprintf("[PATCH /v1alpha1/managementclusters/{fullName.managementClusterName}/provisioners/{fullName.provisionerName}/tanzukubernetesclusters/{fullName.tanzuKubernetesClusterName}/nodepools/{fullName.name}][%d] nodepoolResourceServicePatchOK  %+v", 200, o.Payload)
}

func (o *NodepoolResourceServicePatchOK) String() string {
	return fmt.Sprintf("[PATCH /v1alpha1/managementclusters/{fullName.managementClusterName}/provisioners/{fullName.provisionerName}/tanzukubernetesclusters/{fullName.tanzuKubernetesClusterName}/nodepools/{fullName.name}][%d] nodepoolResourceServicePatchOK  %+v", 200, o.Payload)
}

func (o *NodepoolResourceServicePatchOK) GetPayload() *models.ManagementclusterProvisionerTanzukubernetesclusterNodepoolPatchNodepoolResponse {
	return o.Payload
}

func (o *NodepoolResourceServicePatchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ManagementclusterProvisionerTanzukubernetesclusterNodepoolPatchNodepoolResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNodepoolResourceServicePatchDefault creates a NodepoolResourceServicePatchDefault with default headers values
func NewNodepoolResourceServicePatchDefault(code int) *NodepoolResourceServicePatchDefault {
	return &NodepoolResourceServicePatchDefault{
		_statusCode: code,
	}
}

/*
NodepoolResourceServicePatchDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type NodepoolResourceServicePatchDefault struct {
	_statusCode int

	Payload *models.GrpcGatewayRuntimeError
}

// Code gets the status code for the nodepool resource service patch default response
func (o *NodepoolResourceServicePatchDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this nodepool resource service patch default response has a 2xx status code
func (o *NodepoolResourceServicePatchDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this nodepool resource service patch default response has a 3xx status code
func (o *NodepoolResourceServicePatchDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this nodepool resource service patch default response has a 4xx status code
func (o *NodepoolResourceServicePatchDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this nodepool resource service patch default response has a 5xx status code
func (o *NodepoolResourceServicePatchDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this nodepool resource service patch default response a status code equal to that given
func (o *NodepoolResourceServicePatchDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *NodepoolResourceServicePatchDefault) Error() string {
	return fmt.Sprintf("[PATCH /v1alpha1/managementclusters/{fullName.managementClusterName}/provisioners/{fullName.provisionerName}/tanzukubernetesclusters/{fullName.tanzuKubernetesClusterName}/nodepools/{fullName.name}][%d] NodepoolResourceService_Patch default  %+v", o._statusCode, o.Payload)
}

func (o *NodepoolResourceServicePatchDefault) String() string {
	return fmt.Sprintf("[PATCH /v1alpha1/managementclusters/{fullName.managementClusterName}/provisioners/{fullName.provisionerName}/tanzukubernetesclusters/{fullName.tanzuKubernetesClusterName}/nodepools/{fullName.name}][%d] NodepoolResourceService_Patch default  %+v", o._statusCode, o.Payload)
}

func (o *NodepoolResourceServicePatchDefault) GetPayload() *models.GrpcGatewayRuntimeError {
	return o.Payload
}

func (o *NodepoolResourceServicePatchDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GrpcGatewayRuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
