// Code generated by go-swagger; DO NOT EDIT.

package source_secret_resource_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSourceSecretResourceServiceGetParams creates a new SourceSecretResourceServiceGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSourceSecretResourceServiceGetParams() *SourceSecretResourceServiceGetParams {
	return &SourceSecretResourceServiceGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSourceSecretResourceServiceGetParamsWithTimeout creates a new SourceSecretResourceServiceGetParams object
// with the ability to set a timeout on a request.
func NewSourceSecretResourceServiceGetParamsWithTimeout(timeout time.Duration) *SourceSecretResourceServiceGetParams {
	return &SourceSecretResourceServiceGetParams{
		timeout: timeout,
	}
}

// NewSourceSecretResourceServiceGetParamsWithContext creates a new SourceSecretResourceServiceGetParams object
// with the ability to set a context for a request.
func NewSourceSecretResourceServiceGetParamsWithContext(ctx context.Context) *SourceSecretResourceServiceGetParams {
	return &SourceSecretResourceServiceGetParams{
		Context: ctx,
	}
}

// NewSourceSecretResourceServiceGetParamsWithHTTPClient creates a new SourceSecretResourceServiceGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewSourceSecretResourceServiceGetParamsWithHTTPClient(client *http.Client) *SourceSecretResourceServiceGetParams {
	return &SourceSecretResourceServiceGetParams{
		HTTPClient: client,
	}
}

/*
SourceSecretResourceServiceGetParams contains all the parameters to send to the API endpoint

	for the source secret resource service get operation.

	Typically these are written to a http.Request.
*/
type SourceSecretResourceServiceGetParams struct {

	/* FullNameClusterName.

	   Name of Cluster.
	*/
	FullNameClusterName string

	/* FullNameManagementClusterName.

	   Name of management cluster.
	*/
	FullNameManagementClusterName *string

	/* FullNameName.

	   Name of Source Secret.
	*/
	FullNameName string

	/* FullNameOrgID.

	   ID of Organization.
	*/
	FullNameOrgID *string

	/* FullNameProvisionerName.

	   Name of Provisioner.
	*/
	FullNameProvisionerName *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the source secret resource service get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SourceSecretResourceServiceGetParams) WithDefaults() *SourceSecretResourceServiceGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the source secret resource service get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SourceSecretResourceServiceGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the source secret resource service get params
func (o *SourceSecretResourceServiceGetParams) WithTimeout(timeout time.Duration) *SourceSecretResourceServiceGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the source secret resource service get params
func (o *SourceSecretResourceServiceGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the source secret resource service get params
func (o *SourceSecretResourceServiceGetParams) WithContext(ctx context.Context) *SourceSecretResourceServiceGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the source secret resource service get params
func (o *SourceSecretResourceServiceGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the source secret resource service get params
func (o *SourceSecretResourceServiceGetParams) WithHTTPClient(client *http.Client) *SourceSecretResourceServiceGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the source secret resource service get params
func (o *SourceSecretResourceServiceGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFullNameClusterName adds the fullNameClusterName to the source secret resource service get params
func (o *SourceSecretResourceServiceGetParams) WithFullNameClusterName(fullNameClusterName string) *SourceSecretResourceServiceGetParams {
	o.SetFullNameClusterName(fullNameClusterName)
	return o
}

// SetFullNameClusterName adds the fullNameClusterName to the source secret resource service get params
func (o *SourceSecretResourceServiceGetParams) SetFullNameClusterName(fullNameClusterName string) {
	o.FullNameClusterName = fullNameClusterName
}

// WithFullNameManagementClusterName adds the fullNameManagementClusterName to the source secret resource service get params
func (o *SourceSecretResourceServiceGetParams) WithFullNameManagementClusterName(fullNameManagementClusterName *string) *SourceSecretResourceServiceGetParams {
	o.SetFullNameManagementClusterName(fullNameManagementClusterName)
	return o
}

// SetFullNameManagementClusterName adds the fullNameManagementClusterName to the source secret resource service get params
func (o *SourceSecretResourceServiceGetParams) SetFullNameManagementClusterName(fullNameManagementClusterName *string) {
	o.FullNameManagementClusterName = fullNameManagementClusterName
}

// WithFullNameName adds the fullNameName to the source secret resource service get params
func (o *SourceSecretResourceServiceGetParams) WithFullNameName(fullNameName string) *SourceSecretResourceServiceGetParams {
	o.SetFullNameName(fullNameName)
	return o
}

// SetFullNameName adds the fullNameName to the source secret resource service get params
func (o *SourceSecretResourceServiceGetParams) SetFullNameName(fullNameName string) {
	o.FullNameName = fullNameName
}

// WithFullNameOrgID adds the fullNameOrgID to the source secret resource service get params
func (o *SourceSecretResourceServiceGetParams) WithFullNameOrgID(fullNameOrgID *string) *SourceSecretResourceServiceGetParams {
	o.SetFullNameOrgID(fullNameOrgID)
	return o
}

// SetFullNameOrgID adds the fullNameOrgId to the source secret resource service get params
func (o *SourceSecretResourceServiceGetParams) SetFullNameOrgID(fullNameOrgID *string) {
	o.FullNameOrgID = fullNameOrgID
}

// WithFullNameProvisionerName adds the fullNameProvisionerName to the source secret resource service get params
func (o *SourceSecretResourceServiceGetParams) WithFullNameProvisionerName(fullNameProvisionerName *string) *SourceSecretResourceServiceGetParams {
	o.SetFullNameProvisionerName(fullNameProvisionerName)
	return o
}

// SetFullNameProvisionerName adds the fullNameProvisionerName to the source secret resource service get params
func (o *SourceSecretResourceServiceGetParams) SetFullNameProvisionerName(fullNameProvisionerName *string) {
	o.FullNameProvisionerName = fullNameProvisionerName
}

// WriteToRequest writes these params to a swagger request
func (o *SourceSecretResourceServiceGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param fullName.clusterName
	if err := r.SetPathParam("fullName.clusterName", o.FullNameClusterName); err != nil {
		return err
	}

	if o.FullNameManagementClusterName != nil {

		// query param fullName.managementClusterName
		var qrFullNameManagementClusterName string

		if o.FullNameManagementClusterName != nil {
			qrFullNameManagementClusterName = *o.FullNameManagementClusterName
		}
		qFullNameManagementClusterName := qrFullNameManagementClusterName
		if qFullNameManagementClusterName != "" {

			if err := r.SetQueryParam("fullName.managementClusterName", qFullNameManagementClusterName); err != nil {
				return err
			}
		}
	}

	// path param fullName.name
	if err := r.SetPathParam("fullName.name", o.FullNameName); err != nil {
		return err
	}

	if o.FullNameOrgID != nil {

		// query param fullName.orgId
		var qrFullNameOrgID string

		if o.FullNameOrgID != nil {
			qrFullNameOrgID = *o.FullNameOrgID
		}
		qFullNameOrgID := qrFullNameOrgID
		if qFullNameOrgID != "" {

			if err := r.SetQueryParam("fullName.orgId", qFullNameOrgID); err != nil {
				return err
			}
		}
	}

	if o.FullNameProvisionerName != nil {

		// query param fullName.provisionerName
		var qrFullNameProvisionerName string

		if o.FullNameProvisionerName != nil {
			qrFullNameProvisionerName = *o.FullNameProvisionerName
		}
		qFullNameProvisionerName := qrFullNameProvisionerName
		if qFullNameProvisionerName != "" {

			if err := r.SetQueryParam("fullName.provisionerName", qFullNameProvisionerName); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
