// Code generated by go-swagger; DO NOT EDIT.

package scan_resource_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/warroyo/tmc-go-rest-sdk/models"
)

// NewScanResourceServiceCreateParams creates a new ScanResourceServiceCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewScanResourceServiceCreateParams() *ScanResourceServiceCreateParams {
	return &ScanResourceServiceCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewScanResourceServiceCreateParamsWithTimeout creates a new ScanResourceServiceCreateParams object
// with the ability to set a timeout on a request.
func NewScanResourceServiceCreateParamsWithTimeout(timeout time.Duration) *ScanResourceServiceCreateParams {
	return &ScanResourceServiceCreateParams{
		timeout: timeout,
	}
}

// NewScanResourceServiceCreateParamsWithContext creates a new ScanResourceServiceCreateParams object
// with the ability to set a context for a request.
func NewScanResourceServiceCreateParamsWithContext(ctx context.Context) *ScanResourceServiceCreateParams {
	return &ScanResourceServiceCreateParams{
		Context: ctx,
	}
}

// NewScanResourceServiceCreateParamsWithHTTPClient creates a new ScanResourceServiceCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewScanResourceServiceCreateParamsWithHTTPClient(client *http.Client) *ScanResourceServiceCreateParams {
	return &ScanResourceServiceCreateParams{
		HTTPClient: client,
	}
}

/*
ScanResourceServiceCreateParams contains all the parameters to send to the API endpoint

	for the scan resource service create operation.

	Typically these are written to a http.Request.
*/
type ScanResourceServiceCreateParams struct {

	// Body.
	Body *models.ClusterInspectionScanCreateScanRequest

	/* ScanFullNameClusterName.

	   Name of Cluster.
	*/
	ScanFullNameClusterName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the scan resource service create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ScanResourceServiceCreateParams) WithDefaults() *ScanResourceServiceCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the scan resource service create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ScanResourceServiceCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the scan resource service create params
func (o *ScanResourceServiceCreateParams) WithTimeout(timeout time.Duration) *ScanResourceServiceCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the scan resource service create params
func (o *ScanResourceServiceCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the scan resource service create params
func (o *ScanResourceServiceCreateParams) WithContext(ctx context.Context) *ScanResourceServiceCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the scan resource service create params
func (o *ScanResourceServiceCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the scan resource service create params
func (o *ScanResourceServiceCreateParams) WithHTTPClient(client *http.Client) *ScanResourceServiceCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the scan resource service create params
func (o *ScanResourceServiceCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the scan resource service create params
func (o *ScanResourceServiceCreateParams) WithBody(body *models.ClusterInspectionScanCreateScanRequest) *ScanResourceServiceCreateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the scan resource service create params
func (o *ScanResourceServiceCreateParams) SetBody(body *models.ClusterInspectionScanCreateScanRequest) {
	o.Body = body
}

// WithScanFullNameClusterName adds the scanFullNameClusterName to the scan resource service create params
func (o *ScanResourceServiceCreateParams) WithScanFullNameClusterName(scanFullNameClusterName string) *ScanResourceServiceCreateParams {
	o.SetScanFullNameClusterName(scanFullNameClusterName)
	return o
}

// SetScanFullNameClusterName adds the scanFullNameClusterName to the scan resource service create params
func (o *ScanResourceServiceCreateParams) SetScanFullNameClusterName(scanFullNameClusterName string) {
	o.ScanFullNameClusterName = scanFullNameClusterName
}

// WriteToRequest writes these params to a swagger request
func (o *ScanResourceServiceCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param scan.fullName.clusterName
	if err := r.SetPathParam("scan.fullName.clusterName", o.ScanFullNameClusterName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
