// Code generated by go-swagger; DO NOT EDIT.

package provider_eks_cluster_resource_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewProviderEksClusterResourceServiceGetParams creates a new ProviderEksClusterResourceServiceGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewProviderEksClusterResourceServiceGetParams() *ProviderEksClusterResourceServiceGetParams {
	return &ProviderEksClusterResourceServiceGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewProviderEksClusterResourceServiceGetParamsWithTimeout creates a new ProviderEksClusterResourceServiceGetParams object
// with the ability to set a timeout on a request.
func NewProviderEksClusterResourceServiceGetParamsWithTimeout(timeout time.Duration) *ProviderEksClusterResourceServiceGetParams {
	return &ProviderEksClusterResourceServiceGetParams{
		timeout: timeout,
	}
}

// NewProviderEksClusterResourceServiceGetParamsWithContext creates a new ProviderEksClusterResourceServiceGetParams object
// with the ability to set a context for a request.
func NewProviderEksClusterResourceServiceGetParamsWithContext(ctx context.Context) *ProviderEksClusterResourceServiceGetParams {
	return &ProviderEksClusterResourceServiceGetParams{
		Context: ctx,
	}
}

// NewProviderEksClusterResourceServiceGetParamsWithHTTPClient creates a new ProviderEksClusterResourceServiceGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewProviderEksClusterResourceServiceGetParamsWithHTTPClient(client *http.Client) *ProviderEksClusterResourceServiceGetParams {
	return &ProviderEksClusterResourceServiceGetParams{
		HTTPClient: client,
	}
}

/*
ProviderEksClusterResourceServiceGetParams contains all the parameters to send to the API endpoint

	for the provider eks cluster resource service get operation.

	Typically these are written to a http.Request.
*/
type ProviderEksClusterResourceServiceGetParams struct {

	/* FullNameCredentialName.

	   Name of the credential.
	*/
	FullNameCredentialName *string

	/* FullNameName.

	   Name of this cluster in EKS.
	*/
	FullNameName string

	/* FullNameOrgID.

	   ID of Organization.
	*/
	FullNameOrgID *string

	/* FullNameRegion.

	   Name of the region.
	*/
	FullNameRegion *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the provider eks cluster resource service get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ProviderEksClusterResourceServiceGetParams) WithDefaults() *ProviderEksClusterResourceServiceGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the provider eks cluster resource service get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ProviderEksClusterResourceServiceGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the provider eks cluster resource service get params
func (o *ProviderEksClusterResourceServiceGetParams) WithTimeout(timeout time.Duration) *ProviderEksClusterResourceServiceGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the provider eks cluster resource service get params
func (o *ProviderEksClusterResourceServiceGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the provider eks cluster resource service get params
func (o *ProviderEksClusterResourceServiceGetParams) WithContext(ctx context.Context) *ProviderEksClusterResourceServiceGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the provider eks cluster resource service get params
func (o *ProviderEksClusterResourceServiceGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the provider eks cluster resource service get params
func (o *ProviderEksClusterResourceServiceGetParams) WithHTTPClient(client *http.Client) *ProviderEksClusterResourceServiceGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the provider eks cluster resource service get params
func (o *ProviderEksClusterResourceServiceGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFullNameCredentialName adds the fullNameCredentialName to the provider eks cluster resource service get params
func (o *ProviderEksClusterResourceServiceGetParams) WithFullNameCredentialName(fullNameCredentialName *string) *ProviderEksClusterResourceServiceGetParams {
	o.SetFullNameCredentialName(fullNameCredentialName)
	return o
}

// SetFullNameCredentialName adds the fullNameCredentialName to the provider eks cluster resource service get params
func (o *ProviderEksClusterResourceServiceGetParams) SetFullNameCredentialName(fullNameCredentialName *string) {
	o.FullNameCredentialName = fullNameCredentialName
}

// WithFullNameName adds the fullNameName to the provider eks cluster resource service get params
func (o *ProviderEksClusterResourceServiceGetParams) WithFullNameName(fullNameName string) *ProviderEksClusterResourceServiceGetParams {
	o.SetFullNameName(fullNameName)
	return o
}

// SetFullNameName adds the fullNameName to the provider eks cluster resource service get params
func (o *ProviderEksClusterResourceServiceGetParams) SetFullNameName(fullNameName string) {
	o.FullNameName = fullNameName
}

// WithFullNameOrgID adds the fullNameOrgID to the provider eks cluster resource service get params
func (o *ProviderEksClusterResourceServiceGetParams) WithFullNameOrgID(fullNameOrgID *string) *ProviderEksClusterResourceServiceGetParams {
	o.SetFullNameOrgID(fullNameOrgID)
	return o
}

// SetFullNameOrgID adds the fullNameOrgId to the provider eks cluster resource service get params
func (o *ProviderEksClusterResourceServiceGetParams) SetFullNameOrgID(fullNameOrgID *string) {
	o.FullNameOrgID = fullNameOrgID
}

// WithFullNameRegion adds the fullNameRegion to the provider eks cluster resource service get params
func (o *ProviderEksClusterResourceServiceGetParams) WithFullNameRegion(fullNameRegion *string) *ProviderEksClusterResourceServiceGetParams {
	o.SetFullNameRegion(fullNameRegion)
	return o
}

// SetFullNameRegion adds the fullNameRegion to the provider eks cluster resource service get params
func (o *ProviderEksClusterResourceServiceGetParams) SetFullNameRegion(fullNameRegion *string) {
	o.FullNameRegion = fullNameRegion
}

// WriteToRequest writes these params to a swagger request
func (o *ProviderEksClusterResourceServiceGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.FullNameCredentialName != nil {

		// query param fullName.credentialName
		var qrFullNameCredentialName string

		if o.FullNameCredentialName != nil {
			qrFullNameCredentialName = *o.FullNameCredentialName
		}
		qFullNameCredentialName := qrFullNameCredentialName
		if qFullNameCredentialName != "" {

			if err := r.SetQueryParam("fullName.credentialName", qFullNameCredentialName); err != nil {
				return err
			}
		}
	}

	// path param fullName.name
	if err := r.SetPathParam("fullName.name", o.FullNameName); err != nil {
		return err
	}

	if o.FullNameOrgID != nil {

		// query param fullName.orgId
		var qrFullNameOrgID string

		if o.FullNameOrgID != nil {
			qrFullNameOrgID = *o.FullNameOrgID
		}
		qFullNameOrgID := qrFullNameOrgID
		if qFullNameOrgID != "" {

			if err := r.SetQueryParam("fullName.orgId", qFullNameOrgID); err != nil {
				return err
			}
		}
	}

	if o.FullNameRegion != nil {

		// query param fullName.region
		var qrFullNameRegion string

		if o.FullNameRegion != nil {
			qrFullNameRegion = *o.FullNameRegion
		}
		qFullNameRegion := qrFullNameRegion
		if qFullNameRegion != "" {

			if err := r.SetQueryParam("fullName.region", qFullNameRegion); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
