// Code generated by go-swagger; DO NOT EDIT.

package permission_template_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/warroyo/tmc-go-rest-sdk/models"
)

// PermissionTemplateServiceGenerateReader is a Reader for the PermissionTemplateServiceGenerate structure.
type PermissionTemplateServiceGenerateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PermissionTemplateServiceGenerateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPermissionTemplateServiceGenerateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPermissionTemplateServiceGenerateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPermissionTemplateServiceGenerateOK creates a PermissionTemplateServiceGenerateOK with default headers values
func NewPermissionTemplateServiceGenerateOK() *PermissionTemplateServiceGenerateOK {
	return &PermissionTemplateServiceGenerateOK{}
}

/*
PermissionTemplateServiceGenerateOK describes a response with status code 200, with default header values.

A successful response.
*/
type PermissionTemplateServiceGenerateOK struct {
	Payload *models.AccountManagementclusterProvisionerCredentialGeneratePermissionTemplateResponse
}

// IsSuccess returns true when this permission template service generate o k response has a 2xx status code
func (o *PermissionTemplateServiceGenerateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this permission template service generate o k response has a 3xx status code
func (o *PermissionTemplateServiceGenerateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this permission template service generate o k response has a 4xx status code
func (o *PermissionTemplateServiceGenerateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this permission template service generate o k response has a 5xx status code
func (o *PermissionTemplateServiceGenerateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this permission template service generate o k response a status code equal to that given
func (o *PermissionTemplateServiceGenerateOK) IsCode(code int) bool {
	return code == 200
}

func (o *PermissionTemplateServiceGenerateOK) Error() string {
	return fmt.Sprintf("[POST /v1alpha1/account/managementcluster/provisioner/credentials:permissiontemplate][%d] permissionTemplateServiceGenerateOK  %+v", 200, o.Payload)
}

func (o *PermissionTemplateServiceGenerateOK) String() string {
	return fmt.Sprintf("[POST /v1alpha1/account/managementcluster/provisioner/credentials:permissiontemplate][%d] permissionTemplateServiceGenerateOK  %+v", 200, o.Payload)
}

func (o *PermissionTemplateServiceGenerateOK) GetPayload() *models.AccountManagementclusterProvisionerCredentialGeneratePermissionTemplateResponse {
	return o.Payload
}

func (o *PermissionTemplateServiceGenerateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AccountManagementclusterProvisionerCredentialGeneratePermissionTemplateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPermissionTemplateServiceGenerateDefault creates a PermissionTemplateServiceGenerateDefault with default headers values
func NewPermissionTemplateServiceGenerateDefault(code int) *PermissionTemplateServiceGenerateDefault {
	return &PermissionTemplateServiceGenerateDefault{
		_statusCode: code,
	}
}

/*
PermissionTemplateServiceGenerateDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type PermissionTemplateServiceGenerateDefault struct {
	_statusCode int

	Payload *models.GrpcGatewayRuntimeError
}

// Code gets the status code for the permission template service generate default response
func (o *PermissionTemplateServiceGenerateDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this permission template service generate default response has a 2xx status code
func (o *PermissionTemplateServiceGenerateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this permission template service generate default response has a 3xx status code
func (o *PermissionTemplateServiceGenerateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this permission template service generate default response has a 4xx status code
func (o *PermissionTemplateServiceGenerateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this permission template service generate default response has a 5xx status code
func (o *PermissionTemplateServiceGenerateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this permission template service generate default response a status code equal to that given
func (o *PermissionTemplateServiceGenerateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *PermissionTemplateServiceGenerateDefault) Error() string {
	return fmt.Sprintf("[POST /v1alpha1/account/managementcluster/provisioner/credentials:permissiontemplate][%d] PermissionTemplateService_Generate default  %+v", o._statusCode, o.Payload)
}

func (o *PermissionTemplateServiceGenerateDefault) String() string {
	return fmt.Sprintf("[POST /v1alpha1/account/managementcluster/provisioner/credentials:permissiontemplate][%d] PermissionTemplateService_Generate default  %+v", o._statusCode, o.Payload)
}

func (o *PermissionTemplateServiceGenerateDefault) GetPayload() *models.GrpcGatewayRuntimeError {
	return o.Payload
}

func (o *PermissionTemplateServiceGenerateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GrpcGatewayRuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
