// Code generated by go-swagger; DO NOT EDIT.

package secret_resource_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/warroyo/tmc-go-rest-sdk/models"
)

// SecretResourceServiceGetReader is a Reader for the SecretResourceServiceGet structure.
type SecretResourceServiceGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SecretResourceServiceGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSecretResourceServiceGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSecretResourceServiceGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSecretResourceServiceGetOK creates a SecretResourceServiceGetOK with default headers values
func NewSecretResourceServiceGetOK() *SecretResourceServiceGetOK {
	return &SecretResourceServiceGetOK{}
}

/*
SecretResourceServiceGetOK describes a response with status code 200, with default header values.

A successful response.
*/
type SecretResourceServiceGetOK struct {
	Payload *models.ClusterNamespaceSecretGetSecretResponse
}

// IsSuccess returns true when this secret resource service get o k response has a 2xx status code
func (o *SecretResourceServiceGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this secret resource service get o k response has a 3xx status code
func (o *SecretResourceServiceGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this secret resource service get o k response has a 4xx status code
func (o *SecretResourceServiceGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this secret resource service get o k response has a 5xx status code
func (o *SecretResourceServiceGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this secret resource service get o k response a status code equal to that given
func (o *SecretResourceServiceGetOK) IsCode(code int) bool {
	return code == 200
}

func (o *SecretResourceServiceGetOK) Error() string {
	return fmt.Sprintf("[GET /v1alpha1/clusters/{fullName.clusterName}/namespaces/{fullName.namespaceName}/secrets/{fullName.name}][%d] secretResourceServiceGetOK  %+v", 200, o.Payload)
}

func (o *SecretResourceServiceGetOK) String() string {
	return fmt.Sprintf("[GET /v1alpha1/clusters/{fullName.clusterName}/namespaces/{fullName.namespaceName}/secrets/{fullName.name}][%d] secretResourceServiceGetOK  %+v", 200, o.Payload)
}

func (o *SecretResourceServiceGetOK) GetPayload() *models.ClusterNamespaceSecretGetSecretResponse {
	return o.Payload
}

func (o *SecretResourceServiceGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ClusterNamespaceSecretGetSecretResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSecretResourceServiceGetDefault creates a SecretResourceServiceGetDefault with default headers values
func NewSecretResourceServiceGetDefault(code int) *SecretResourceServiceGetDefault {
	return &SecretResourceServiceGetDefault{
		_statusCode: code,
	}
}

/*
SecretResourceServiceGetDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type SecretResourceServiceGetDefault struct {
	_statusCode int

	Payload *models.GrpcGatewayRuntimeError
}

// Code gets the status code for the secret resource service get default response
func (o *SecretResourceServiceGetDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this secret resource service get default response has a 2xx status code
func (o *SecretResourceServiceGetDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this secret resource service get default response has a 3xx status code
func (o *SecretResourceServiceGetDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this secret resource service get default response has a 4xx status code
func (o *SecretResourceServiceGetDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this secret resource service get default response has a 5xx status code
func (o *SecretResourceServiceGetDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this secret resource service get default response a status code equal to that given
func (o *SecretResourceServiceGetDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *SecretResourceServiceGetDefault) Error() string {
	return fmt.Sprintf("[GET /v1alpha1/clusters/{fullName.clusterName}/namespaces/{fullName.namespaceName}/secrets/{fullName.name}][%d] SecretResourceService_Get default  %+v", o._statusCode, o.Payload)
}

func (o *SecretResourceServiceGetDefault) String() string {
	return fmt.Sprintf("[GET /v1alpha1/clusters/{fullName.clusterName}/namespaces/{fullName.namespaceName}/secrets/{fullName.name}][%d] SecretResourceService_Get default  %+v", o._statusCode, o.Payload)
}

func (o *SecretResourceServiceGetDefault) GetPayload() *models.GrpcGatewayRuntimeError {
	return o.Payload
}

func (o *SecretResourceServiceGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GrpcGatewayRuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
