// Code generated by go-swagger; DO NOT EDIT.

package provider_eks_cluster_i_a_m_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/warroyo/tmc-go-rest-sdk/models"
)

// ProviderEksClusterIAMPolicyPatchReader is a Reader for the ProviderEksClusterIAMPolicyPatch structure.
type ProviderEksClusterIAMPolicyPatchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProviderEksClusterIAMPolicyPatchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewProviderEksClusterIAMPolicyPatchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewProviderEksClusterIAMPolicyPatchDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewProviderEksClusterIAMPolicyPatchOK creates a ProviderEksClusterIAMPolicyPatchOK with default headers values
func NewProviderEksClusterIAMPolicyPatchOK() *ProviderEksClusterIAMPolicyPatchOK {
	return &ProviderEksClusterIAMPolicyPatchOK{}
}

/*
ProviderEksClusterIAMPolicyPatchOK describes a response with status code 200, with default header values.

A successful response.
*/
type ProviderEksClusterIAMPolicyPatchOK struct {
	Payload *models.ManageEksProvidereksclusterPatchProviderEksClusterIAMPolicyResponse
}

// IsSuccess returns true when this provider eks cluster i a m policy patch o k response has a 2xx status code
func (o *ProviderEksClusterIAMPolicyPatchOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this provider eks cluster i a m policy patch o k response has a 3xx status code
func (o *ProviderEksClusterIAMPolicyPatchOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this provider eks cluster i a m policy patch o k response has a 4xx status code
func (o *ProviderEksClusterIAMPolicyPatchOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this provider eks cluster i a m policy patch o k response has a 5xx status code
func (o *ProviderEksClusterIAMPolicyPatchOK) IsServerError() bool {
	return false
}

// IsCode returns true when this provider eks cluster i a m policy patch o k response a status code equal to that given
func (o *ProviderEksClusterIAMPolicyPatchOK) IsCode(code int) bool {
	return code == 200
}

func (o *ProviderEksClusterIAMPolicyPatchOK) Error() string {
	return fmt.Sprintf("[PATCH /v1alpha1/manage/providereksclusters:iam/{fullName.name}][%d] providerEksClusterIAMPolicyPatchOK  %+v", 200, o.Payload)
}

func (o *ProviderEksClusterIAMPolicyPatchOK) String() string {
	return fmt.Sprintf("[PATCH /v1alpha1/manage/providereksclusters:iam/{fullName.name}][%d] providerEksClusterIAMPolicyPatchOK  %+v", 200, o.Payload)
}

func (o *ProviderEksClusterIAMPolicyPatchOK) GetPayload() *models.ManageEksProvidereksclusterPatchProviderEksClusterIAMPolicyResponse {
	return o.Payload
}

func (o *ProviderEksClusterIAMPolicyPatchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ManageEksProvidereksclusterPatchProviderEksClusterIAMPolicyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProviderEksClusterIAMPolicyPatchDefault creates a ProviderEksClusterIAMPolicyPatchDefault with default headers values
func NewProviderEksClusterIAMPolicyPatchDefault(code int) *ProviderEksClusterIAMPolicyPatchDefault {
	return &ProviderEksClusterIAMPolicyPatchDefault{
		_statusCode: code,
	}
}

/*
ProviderEksClusterIAMPolicyPatchDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ProviderEksClusterIAMPolicyPatchDefault struct {
	_statusCode int

	Payload *models.GrpcGatewayRuntimeError
}

// Code gets the status code for the provider eks cluster i a m policy patch default response
func (o *ProviderEksClusterIAMPolicyPatchDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this provider eks cluster i a m policy patch default response has a 2xx status code
func (o *ProviderEksClusterIAMPolicyPatchDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this provider eks cluster i a m policy patch default response has a 3xx status code
func (o *ProviderEksClusterIAMPolicyPatchDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this provider eks cluster i a m policy patch default response has a 4xx status code
func (o *ProviderEksClusterIAMPolicyPatchDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this provider eks cluster i a m policy patch default response has a 5xx status code
func (o *ProviderEksClusterIAMPolicyPatchDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this provider eks cluster i a m policy patch default response a status code equal to that given
func (o *ProviderEksClusterIAMPolicyPatchDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ProviderEksClusterIAMPolicyPatchDefault) Error() string {
	return fmt.Sprintf("[PATCH /v1alpha1/manage/providereksclusters:iam/{fullName.name}][%d] ProviderEksClusterIAMPolicy_Patch default  %+v", o._statusCode, o.Payload)
}

func (o *ProviderEksClusterIAMPolicyPatchDefault) String() string {
	return fmt.Sprintf("[PATCH /v1alpha1/manage/providereksclusters:iam/{fullName.name}][%d] ProviderEksClusterIAMPolicy_Patch default  %+v", o._statusCode, o.Payload)
}

func (o *ProviderEksClusterIAMPolicyPatchDefault) GetPayload() *models.GrpcGatewayRuntimeError {
	return o.Payload
}

func (o *ProviderEksClusterIAMPolicyPatchDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GrpcGatewayRuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
