// Code generated by go-swagger; DO NOT EDIT.

package eula_resource_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/warroyo/tmc-go-rest-sdk/models"
)

// NewEulaResourceServiceAcceptParams creates a new EulaResourceServiceAcceptParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEulaResourceServiceAcceptParams() *EulaResourceServiceAcceptParams {
	return &EulaResourceServiceAcceptParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewEulaResourceServiceAcceptParamsWithTimeout creates a new EulaResourceServiceAcceptParams object
// with the ability to set a timeout on a request.
func NewEulaResourceServiceAcceptParamsWithTimeout(timeout time.Duration) *EulaResourceServiceAcceptParams {
	return &EulaResourceServiceAcceptParams{
		timeout: timeout,
	}
}

// NewEulaResourceServiceAcceptParamsWithContext creates a new EulaResourceServiceAcceptParams object
// with the ability to set a context for a request.
func NewEulaResourceServiceAcceptParamsWithContext(ctx context.Context) *EulaResourceServiceAcceptParams {
	return &EulaResourceServiceAcceptParams{
		Context: ctx,
	}
}

// NewEulaResourceServiceAcceptParamsWithHTTPClient creates a new EulaResourceServiceAcceptParams object
// with the ability to set a custom HTTPClient for a request.
func NewEulaResourceServiceAcceptParamsWithHTTPClient(client *http.Client) *EulaResourceServiceAcceptParams {
	return &EulaResourceServiceAcceptParams{
		HTTPClient: client,
	}
}

/*
EulaResourceServiceAcceptParams contains all the parameters to send to the API endpoint

	for the eula resource service accept operation.

	Typically these are written to a http.Request.
*/
type EulaResourceServiceAcceptParams struct {

	// Body.
	Body *models.TanzupackageTapEulaAcceptEulaRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the eula resource service accept params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EulaResourceServiceAcceptParams) WithDefaults() *EulaResourceServiceAcceptParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the eula resource service accept params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EulaResourceServiceAcceptParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the eula resource service accept params
func (o *EulaResourceServiceAcceptParams) WithTimeout(timeout time.Duration) *EulaResourceServiceAcceptParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the eula resource service accept params
func (o *EulaResourceServiceAcceptParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the eula resource service accept params
func (o *EulaResourceServiceAcceptParams) WithContext(ctx context.Context) *EulaResourceServiceAcceptParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the eula resource service accept params
func (o *EulaResourceServiceAcceptParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the eula resource service accept params
func (o *EulaResourceServiceAcceptParams) WithHTTPClient(client *http.Client) *EulaResourceServiceAcceptParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the eula resource service accept params
func (o *EulaResourceServiceAcceptParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the eula resource service accept params
func (o *EulaResourceServiceAcceptParams) WithBody(body *models.TanzupackageTapEulaAcceptEulaRequest) *EulaResourceServiceAcceptParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the eula resource service accept params
func (o *EulaResourceServiceAcceptParams) SetBody(body *models.TanzupackageTapEulaAcceptEulaRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *EulaResourceServiceAcceptParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
