// Code generated by go-swagger; DO NOT EDIT.

package eula_resource_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/warroyo/tmc-go-rest-sdk/models"
)

// EulaResourceServiceValidateReader is a Reader for the EulaResourceServiceValidate structure.
type EulaResourceServiceValidateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EulaResourceServiceValidateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewEulaResourceServiceValidateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewEulaResourceServiceValidateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEulaResourceServiceValidateOK creates a EulaResourceServiceValidateOK with default headers values
func NewEulaResourceServiceValidateOK() *EulaResourceServiceValidateOK {
	return &EulaResourceServiceValidateOK{}
}

/*
EulaResourceServiceValidateOK describes a response with status code 200, with default header values.

A successful response.
*/
type EulaResourceServiceValidateOK struct {
	Payload *models.TanzupackageTapEulaValidateEulaResponse
}

// IsSuccess returns true when this eula resource service validate o k response has a 2xx status code
func (o *EulaResourceServiceValidateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this eula resource service validate o k response has a 3xx status code
func (o *EulaResourceServiceValidateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this eula resource service validate o k response has a 4xx status code
func (o *EulaResourceServiceValidateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this eula resource service validate o k response has a 5xx status code
func (o *EulaResourceServiceValidateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this eula resource service validate o k response a status code equal to that given
func (o *EulaResourceServiceValidateOK) IsCode(code int) bool {
	return code == 200
}

func (o *EulaResourceServiceValidateOK) Error() string {
	return fmt.Sprintf("[GET /v1alpha1/tanzupackage/tap/eulas][%d] eulaResourceServiceValidateOK  %+v", 200, o.Payload)
}

func (o *EulaResourceServiceValidateOK) String() string {
	return fmt.Sprintf("[GET /v1alpha1/tanzupackage/tap/eulas][%d] eulaResourceServiceValidateOK  %+v", 200, o.Payload)
}

func (o *EulaResourceServiceValidateOK) GetPayload() *models.TanzupackageTapEulaValidateEulaResponse {
	return o.Payload
}

func (o *EulaResourceServiceValidateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TanzupackageTapEulaValidateEulaResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEulaResourceServiceValidateDefault creates a EulaResourceServiceValidateDefault with default headers values
func NewEulaResourceServiceValidateDefault(code int) *EulaResourceServiceValidateDefault {
	return &EulaResourceServiceValidateDefault{
		_statusCode: code,
	}
}

/*
EulaResourceServiceValidateDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type EulaResourceServiceValidateDefault struct {
	_statusCode int

	Payload *models.GrpcGatewayRuntimeError
}

// Code gets the status code for the eula resource service validate default response
func (o *EulaResourceServiceValidateDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this eula resource service validate default response has a 2xx status code
func (o *EulaResourceServiceValidateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this eula resource service validate default response has a 3xx status code
func (o *EulaResourceServiceValidateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this eula resource service validate default response has a 4xx status code
func (o *EulaResourceServiceValidateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this eula resource service validate default response has a 5xx status code
func (o *EulaResourceServiceValidateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this eula resource service validate default response a status code equal to that given
func (o *EulaResourceServiceValidateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *EulaResourceServiceValidateDefault) Error() string {
	return fmt.Sprintf("[GET /v1alpha1/tanzupackage/tap/eulas][%d] EulaResourceService_Validate default  %+v", o._statusCode, o.Payload)
}

func (o *EulaResourceServiceValidateDefault) String() string {
	return fmt.Sprintf("[GET /v1alpha1/tanzupackage/tap/eulas][%d] EulaResourceService_Validate default  %+v", o._statusCode, o.Payload)
}

func (o *EulaResourceServiceValidateDefault) GetPayload() *models.GrpcGatewayRuntimeError {
	return o.Payload
}

func (o *EulaResourceServiceValidateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GrpcGatewayRuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
