// Code generated by go-swagger; DO NOT EDIT.

package backup_resource_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/warroyo/tmc-go-rest-sdk/models"
)

// BackupResourceServiceListReader is a Reader for the BackupResourceServiceList structure.
type BackupResourceServiceListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BackupResourceServiceListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewBackupResourceServiceListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewBackupResourceServiceListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewBackupResourceServiceListOK creates a BackupResourceServiceListOK with default headers values
func NewBackupResourceServiceListOK() *BackupResourceServiceListOK {
	return &BackupResourceServiceListOK{}
}

/*
BackupResourceServiceListOK describes a response with status code 200, with default header values.

A successful response.
*/
type BackupResourceServiceListOK struct {
	Payload *models.ClusterDataprotectionBackupListBackupsResponse
}

// IsSuccess returns true when this backup resource service list o k response has a 2xx status code
func (o *BackupResourceServiceListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this backup resource service list o k response has a 3xx status code
func (o *BackupResourceServiceListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this backup resource service list o k response has a 4xx status code
func (o *BackupResourceServiceListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this backup resource service list o k response has a 5xx status code
func (o *BackupResourceServiceListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this backup resource service list o k response a status code equal to that given
func (o *BackupResourceServiceListOK) IsCode(code int) bool {
	return code == 200
}

func (o *BackupResourceServiceListOK) Error() string {
	return fmt.Sprintf("[GET /v1alpha1/clusters/{searchScope.clusterName}/dataprotection/backups][%d] backupResourceServiceListOK  %+v", 200, o.Payload)
}

func (o *BackupResourceServiceListOK) String() string {
	return fmt.Sprintf("[GET /v1alpha1/clusters/{searchScope.clusterName}/dataprotection/backups][%d] backupResourceServiceListOK  %+v", 200, o.Payload)
}

func (o *BackupResourceServiceListOK) GetPayload() *models.ClusterDataprotectionBackupListBackupsResponse {
	return o.Payload
}

func (o *BackupResourceServiceListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ClusterDataprotectionBackupListBackupsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBackupResourceServiceListDefault creates a BackupResourceServiceListDefault with default headers values
func NewBackupResourceServiceListDefault(code int) *BackupResourceServiceListDefault {
	return &BackupResourceServiceListDefault{
		_statusCode: code,
	}
}

/*
BackupResourceServiceListDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type BackupResourceServiceListDefault struct {
	_statusCode int

	Payload *models.GrpcGatewayRuntimeError
}

// Code gets the status code for the backup resource service list default response
func (o *BackupResourceServiceListDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this backup resource service list default response has a 2xx status code
func (o *BackupResourceServiceListDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this backup resource service list default response has a 3xx status code
func (o *BackupResourceServiceListDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this backup resource service list default response has a 4xx status code
func (o *BackupResourceServiceListDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this backup resource service list default response has a 5xx status code
func (o *BackupResourceServiceListDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this backup resource service list default response a status code equal to that given
func (o *BackupResourceServiceListDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *BackupResourceServiceListDefault) Error() string {
	return fmt.Sprintf("[GET /v1alpha1/clusters/{searchScope.clusterName}/dataprotection/backups][%d] BackupResourceService_List default  %+v", o._statusCode, o.Payload)
}

func (o *BackupResourceServiceListDefault) String() string {
	return fmt.Sprintf("[GET /v1alpha1/clusters/{searchScope.clusterName}/dataprotection/backups][%d] BackupResourceService_List default  %+v", o._statusCode, o.Payload)
}

func (o *BackupResourceServiceListDefault) GetPayload() *models.GrpcGatewayRuntimeError {
	return o.Payload
}

func (o *BackupResourceServiceListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GrpcGatewayRuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
