// Code generated by go-swagger; DO NOT EDIT.

package admin_kubeconfig_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAdminKubeconfigServiceGetAdminKubeconfigParams creates a new AdminKubeconfigServiceGetAdminKubeconfigParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAdminKubeconfigServiceGetAdminKubeconfigParams() *AdminKubeconfigServiceGetAdminKubeconfigParams {
	return &AdminKubeconfigServiceGetAdminKubeconfigParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAdminKubeconfigServiceGetAdminKubeconfigParamsWithTimeout creates a new AdminKubeconfigServiceGetAdminKubeconfigParams object
// with the ability to set a timeout on a request.
func NewAdminKubeconfigServiceGetAdminKubeconfigParamsWithTimeout(timeout time.Duration) *AdminKubeconfigServiceGetAdminKubeconfigParams {
	return &AdminKubeconfigServiceGetAdminKubeconfigParams{
		timeout: timeout,
	}
}

// NewAdminKubeconfigServiceGetAdminKubeconfigParamsWithContext creates a new AdminKubeconfigServiceGetAdminKubeconfigParams object
// with the ability to set a context for a request.
func NewAdminKubeconfigServiceGetAdminKubeconfigParamsWithContext(ctx context.Context) *AdminKubeconfigServiceGetAdminKubeconfigParams {
	return &AdminKubeconfigServiceGetAdminKubeconfigParams{
		Context: ctx,
	}
}

// NewAdminKubeconfigServiceGetAdminKubeconfigParamsWithHTTPClient creates a new AdminKubeconfigServiceGetAdminKubeconfigParams object
// with the ability to set a custom HTTPClient for a request.
func NewAdminKubeconfigServiceGetAdminKubeconfigParamsWithHTTPClient(client *http.Client) *AdminKubeconfigServiceGetAdminKubeconfigParams {
	return &AdminKubeconfigServiceGetAdminKubeconfigParams{
		HTTPClient: client,
	}
}

/*
AdminKubeconfigServiceGetAdminKubeconfigParams contains all the parameters to send to the API endpoint

	for the admin kubeconfig service get admin kubeconfig operation.

	Typically these are written to a http.Request.
*/
type AdminKubeconfigServiceGetAdminKubeconfigParams struct {

	/* EncryptionKeyPublicKeyPem.

	   The RSA public key encoded in PEM format.
	*/
	EncryptionKeyPublicKeyPem *string

	/* EncryptionKeyTimestamp.

	   The timestamp as when the keys were generated.

	   Format: date-time
	*/
	EncryptionKeyTimestamp *strfmt.DateTime

	/* FullNameManagementClusterName.

	   Name of the management cluster.
	*/
	FullNameManagementClusterName *string

	/* FullNameName.

	   Name of this cluster.
	*/
	FullNameName string

	/* FullNameOrgID.

	   ID of Organization.
	*/
	FullNameOrgID *string

	/* FullNameProvisionerName.

	   Provisioner of the cluster.
	*/
	FullNameProvisionerName *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the admin kubeconfig service get admin kubeconfig params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AdminKubeconfigServiceGetAdminKubeconfigParams) WithDefaults() *AdminKubeconfigServiceGetAdminKubeconfigParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the admin kubeconfig service get admin kubeconfig params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AdminKubeconfigServiceGetAdminKubeconfigParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the admin kubeconfig service get admin kubeconfig params
func (o *AdminKubeconfigServiceGetAdminKubeconfigParams) WithTimeout(timeout time.Duration) *AdminKubeconfigServiceGetAdminKubeconfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the admin kubeconfig service get admin kubeconfig params
func (o *AdminKubeconfigServiceGetAdminKubeconfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the admin kubeconfig service get admin kubeconfig params
func (o *AdminKubeconfigServiceGetAdminKubeconfigParams) WithContext(ctx context.Context) *AdminKubeconfigServiceGetAdminKubeconfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the admin kubeconfig service get admin kubeconfig params
func (o *AdminKubeconfigServiceGetAdminKubeconfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the admin kubeconfig service get admin kubeconfig params
func (o *AdminKubeconfigServiceGetAdminKubeconfigParams) WithHTTPClient(client *http.Client) *AdminKubeconfigServiceGetAdminKubeconfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the admin kubeconfig service get admin kubeconfig params
func (o *AdminKubeconfigServiceGetAdminKubeconfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEncryptionKeyPublicKeyPem adds the encryptionKeyPublicKeyPem to the admin kubeconfig service get admin kubeconfig params
func (o *AdminKubeconfigServiceGetAdminKubeconfigParams) WithEncryptionKeyPublicKeyPem(encryptionKeyPublicKeyPem *string) *AdminKubeconfigServiceGetAdminKubeconfigParams {
	o.SetEncryptionKeyPublicKeyPem(encryptionKeyPublicKeyPem)
	return o
}

// SetEncryptionKeyPublicKeyPem adds the encryptionKeyPublicKeyPem to the admin kubeconfig service get admin kubeconfig params
func (o *AdminKubeconfigServiceGetAdminKubeconfigParams) SetEncryptionKeyPublicKeyPem(encryptionKeyPublicKeyPem *string) {
	o.EncryptionKeyPublicKeyPem = encryptionKeyPublicKeyPem
}

// WithEncryptionKeyTimestamp adds the encryptionKeyTimestamp to the admin kubeconfig service get admin kubeconfig params
func (o *AdminKubeconfigServiceGetAdminKubeconfigParams) WithEncryptionKeyTimestamp(encryptionKeyTimestamp *strfmt.DateTime) *AdminKubeconfigServiceGetAdminKubeconfigParams {
	o.SetEncryptionKeyTimestamp(encryptionKeyTimestamp)
	return o
}

// SetEncryptionKeyTimestamp adds the encryptionKeyTimestamp to the admin kubeconfig service get admin kubeconfig params
func (o *AdminKubeconfigServiceGetAdminKubeconfigParams) SetEncryptionKeyTimestamp(encryptionKeyTimestamp *strfmt.DateTime) {
	o.EncryptionKeyTimestamp = encryptionKeyTimestamp
}

// WithFullNameManagementClusterName adds the fullNameManagementClusterName to the admin kubeconfig service get admin kubeconfig params
func (o *AdminKubeconfigServiceGetAdminKubeconfigParams) WithFullNameManagementClusterName(fullNameManagementClusterName *string) *AdminKubeconfigServiceGetAdminKubeconfigParams {
	o.SetFullNameManagementClusterName(fullNameManagementClusterName)
	return o
}

// SetFullNameManagementClusterName adds the fullNameManagementClusterName to the admin kubeconfig service get admin kubeconfig params
func (o *AdminKubeconfigServiceGetAdminKubeconfigParams) SetFullNameManagementClusterName(fullNameManagementClusterName *string) {
	o.FullNameManagementClusterName = fullNameManagementClusterName
}

// WithFullNameName adds the fullNameName to the admin kubeconfig service get admin kubeconfig params
func (o *AdminKubeconfigServiceGetAdminKubeconfigParams) WithFullNameName(fullNameName string) *AdminKubeconfigServiceGetAdminKubeconfigParams {
	o.SetFullNameName(fullNameName)
	return o
}

// SetFullNameName adds the fullNameName to the admin kubeconfig service get admin kubeconfig params
func (o *AdminKubeconfigServiceGetAdminKubeconfigParams) SetFullNameName(fullNameName string) {
	o.FullNameName = fullNameName
}

// WithFullNameOrgID adds the fullNameOrgID to the admin kubeconfig service get admin kubeconfig params
func (o *AdminKubeconfigServiceGetAdminKubeconfigParams) WithFullNameOrgID(fullNameOrgID *string) *AdminKubeconfigServiceGetAdminKubeconfigParams {
	o.SetFullNameOrgID(fullNameOrgID)
	return o
}

// SetFullNameOrgID adds the fullNameOrgId to the admin kubeconfig service get admin kubeconfig params
func (o *AdminKubeconfigServiceGetAdminKubeconfigParams) SetFullNameOrgID(fullNameOrgID *string) {
	o.FullNameOrgID = fullNameOrgID
}

// WithFullNameProvisionerName adds the fullNameProvisionerName to the admin kubeconfig service get admin kubeconfig params
func (o *AdminKubeconfigServiceGetAdminKubeconfigParams) WithFullNameProvisionerName(fullNameProvisionerName *string) *AdminKubeconfigServiceGetAdminKubeconfigParams {
	o.SetFullNameProvisionerName(fullNameProvisionerName)
	return o
}

// SetFullNameProvisionerName adds the fullNameProvisionerName to the admin kubeconfig service get admin kubeconfig params
func (o *AdminKubeconfigServiceGetAdminKubeconfigParams) SetFullNameProvisionerName(fullNameProvisionerName *string) {
	o.FullNameProvisionerName = fullNameProvisionerName
}

// WriteToRequest writes these params to a swagger request
func (o *AdminKubeconfigServiceGetAdminKubeconfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.EncryptionKeyPublicKeyPem != nil {

		// query param encryptionKey.PublicKeyPem
		var qrEncryptionKeyPublicKeyPem string

		if o.EncryptionKeyPublicKeyPem != nil {
			qrEncryptionKeyPublicKeyPem = *o.EncryptionKeyPublicKeyPem
		}
		qEncryptionKeyPublicKeyPem := qrEncryptionKeyPublicKeyPem
		if qEncryptionKeyPublicKeyPem != "" {

			if err := r.SetQueryParam("encryptionKey.PublicKeyPem", qEncryptionKeyPublicKeyPem); err != nil {
				return err
			}
		}
	}

	if o.EncryptionKeyTimestamp != nil {

		// query param encryptionKey.timestamp
		var qrEncryptionKeyTimestamp strfmt.DateTime

		if o.EncryptionKeyTimestamp != nil {
			qrEncryptionKeyTimestamp = *o.EncryptionKeyTimestamp
		}
		qEncryptionKeyTimestamp := qrEncryptionKeyTimestamp.String()
		if qEncryptionKeyTimestamp != "" {

			if err := r.SetQueryParam("encryptionKey.timestamp", qEncryptionKeyTimestamp); err != nil {
				return err
			}
		}
	}

	if o.FullNameManagementClusterName != nil {

		// query param fullName.managementClusterName
		var qrFullNameManagementClusterName string

		if o.FullNameManagementClusterName != nil {
			qrFullNameManagementClusterName = *o.FullNameManagementClusterName
		}
		qFullNameManagementClusterName := qrFullNameManagementClusterName
		if qFullNameManagementClusterName != "" {

			if err := r.SetQueryParam("fullName.managementClusterName", qFullNameManagementClusterName); err != nil {
				return err
			}
		}
	}

	// path param fullName.name
	if err := r.SetPathParam("fullName.name", o.FullNameName); err != nil {
		return err
	}

	if o.FullNameOrgID != nil {

		// query param fullName.orgId
		var qrFullNameOrgID string

		if o.FullNameOrgID != nil {
			qrFullNameOrgID = *o.FullNameOrgID
		}
		qFullNameOrgID := qrFullNameOrgID
		if qFullNameOrgID != "" {

			if err := r.SetQueryParam("fullName.orgId", qFullNameOrgID); err != nil {
				return err
			}
		}
	}

	if o.FullNameProvisionerName != nil {

		// query param fullName.provisionerName
		var qrFullNameProvisionerName string

		if o.FullNameProvisionerName != nil {
			qrFullNameProvisionerName = *o.FullNameProvisionerName
		}
		qFullNameProvisionerName := qrFullNameProvisionerName
		if qFullNameProvisionerName != "" {

			if err := r.SetQueryParam("fullName.provisionerName", qFullNameProvisionerName); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
