// Code generated by go-swagger; DO NOT EDIT.

package credential_resource_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/warroyo/tmc-go-rest-sdk/models"
)

// NewCredentialResourceServiceCreateParams creates a new CredentialResourceServiceCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCredentialResourceServiceCreateParams() *CredentialResourceServiceCreateParams {
	return &CredentialResourceServiceCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCredentialResourceServiceCreateParamsWithTimeout creates a new CredentialResourceServiceCreateParams object
// with the ability to set a timeout on a request.
func NewCredentialResourceServiceCreateParamsWithTimeout(timeout time.Duration) *CredentialResourceServiceCreateParams {
	return &CredentialResourceServiceCreateParams{
		timeout: timeout,
	}
}

// NewCredentialResourceServiceCreateParamsWithContext creates a new CredentialResourceServiceCreateParams object
// with the ability to set a context for a request.
func NewCredentialResourceServiceCreateParamsWithContext(ctx context.Context) *CredentialResourceServiceCreateParams {
	return &CredentialResourceServiceCreateParams{
		Context: ctx,
	}
}

// NewCredentialResourceServiceCreateParamsWithHTTPClient creates a new CredentialResourceServiceCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewCredentialResourceServiceCreateParamsWithHTTPClient(client *http.Client) *CredentialResourceServiceCreateParams {
	return &CredentialResourceServiceCreateParams{
		HTTPClient: client,
	}
}

/*
CredentialResourceServiceCreateParams contains all the parameters to send to the API endpoint

	for the credential resource service create operation.

	Typically these are written to a http.Request.
*/
type CredentialResourceServiceCreateParams struct {

	// Body.
	Body *models.AccountManagementclusterProvisionerCredentialCreateCredentialRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the credential resource service create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CredentialResourceServiceCreateParams) WithDefaults() *CredentialResourceServiceCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the credential resource service create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CredentialResourceServiceCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the credential resource service create params
func (o *CredentialResourceServiceCreateParams) WithTimeout(timeout time.Duration) *CredentialResourceServiceCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the credential resource service create params
func (o *CredentialResourceServiceCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the credential resource service create params
func (o *CredentialResourceServiceCreateParams) WithContext(ctx context.Context) *CredentialResourceServiceCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the credential resource service create params
func (o *CredentialResourceServiceCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the credential resource service create params
func (o *CredentialResourceServiceCreateParams) WithHTTPClient(client *http.Client) *CredentialResourceServiceCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the credential resource service create params
func (o *CredentialResourceServiceCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the credential resource service create params
func (o *CredentialResourceServiceCreateParams) WithBody(body *models.AccountManagementclusterProvisionerCredentialCreateCredentialRequest) *CredentialResourceServiceCreateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the credential resource service create params
func (o *CredentialResourceServiceCreateParams) SetBody(body *models.AccountManagementclusterProvisionerCredentialCreateCredentialRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CredentialResourceServiceCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
