// Code generated by go-swagger; DO NOT EDIT.

package credential_resource_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/warroyo/tmc-go-rest-sdk/models"
)

// CredentialResourceServiceCreateReader is a Reader for the CredentialResourceServiceCreate structure.
type CredentialResourceServiceCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CredentialResourceServiceCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCredentialResourceServiceCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCredentialResourceServiceCreateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCredentialResourceServiceCreateOK creates a CredentialResourceServiceCreateOK with default headers values
func NewCredentialResourceServiceCreateOK() *CredentialResourceServiceCreateOK {
	return &CredentialResourceServiceCreateOK{}
}

/*
CredentialResourceServiceCreateOK describes a response with status code 200, with default header values.

A successful response.
*/
type CredentialResourceServiceCreateOK struct {
	Payload *models.AccountManagementclusterProvisionerCredentialCreateCredentialResponse
}

// IsSuccess returns true when this credential resource service create o k response has a 2xx status code
func (o *CredentialResourceServiceCreateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this credential resource service create o k response has a 3xx status code
func (o *CredentialResourceServiceCreateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this credential resource service create o k response has a 4xx status code
func (o *CredentialResourceServiceCreateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this credential resource service create o k response has a 5xx status code
func (o *CredentialResourceServiceCreateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this credential resource service create o k response a status code equal to that given
func (o *CredentialResourceServiceCreateOK) IsCode(code int) bool {
	return code == 200
}

func (o *CredentialResourceServiceCreateOK) Error() string {
	return fmt.Sprintf("[POST /v1alpha1/account/managementcluster/provisioner/credentials][%d] credentialResourceServiceCreateOK  %+v", 200, o.Payload)
}

func (o *CredentialResourceServiceCreateOK) String() string {
	return fmt.Sprintf("[POST /v1alpha1/account/managementcluster/provisioner/credentials][%d] credentialResourceServiceCreateOK  %+v", 200, o.Payload)
}

func (o *CredentialResourceServiceCreateOK) GetPayload() *models.AccountManagementclusterProvisionerCredentialCreateCredentialResponse {
	return o.Payload
}

func (o *CredentialResourceServiceCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AccountManagementclusterProvisionerCredentialCreateCredentialResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCredentialResourceServiceCreateDefault creates a CredentialResourceServiceCreateDefault with default headers values
func NewCredentialResourceServiceCreateDefault(code int) *CredentialResourceServiceCreateDefault {
	return &CredentialResourceServiceCreateDefault{
		_statusCode: code,
	}
}

/*
CredentialResourceServiceCreateDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type CredentialResourceServiceCreateDefault struct {
	_statusCode int

	Payload *models.GrpcGatewayRuntimeError
}

// Code gets the status code for the credential resource service create default response
func (o *CredentialResourceServiceCreateDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this credential resource service create default response has a 2xx status code
func (o *CredentialResourceServiceCreateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this credential resource service create default response has a 3xx status code
func (o *CredentialResourceServiceCreateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this credential resource service create default response has a 4xx status code
func (o *CredentialResourceServiceCreateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this credential resource service create default response has a 5xx status code
func (o *CredentialResourceServiceCreateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this credential resource service create default response a status code equal to that given
func (o *CredentialResourceServiceCreateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *CredentialResourceServiceCreateDefault) Error() string {
	return fmt.Sprintf("[POST /v1alpha1/account/managementcluster/provisioner/credentials][%d] CredentialResourceService_Create default  %+v", o._statusCode, o.Payload)
}

func (o *CredentialResourceServiceCreateDefault) String() string {
	return fmt.Sprintf("[POST /v1alpha1/account/managementcluster/provisioner/credentials][%d] CredentialResourceService_Create default  %+v", o._statusCode, o.Payload)
}

func (o *CredentialResourceServiceCreateDefault) GetPayload() *models.GrpcGatewayRuntimeError {
	return o.Payload
}

func (o *CredentialResourceServiceCreateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GrpcGatewayRuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
