// Code generated by go-swagger; DO NOT EDIT.

package workspace_i_a_m_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/warroyo/tmc-go-rest-sdk/models"
)

// WorkspaceIAMPolicyGetReader is a Reader for the WorkspaceIAMPolicyGet structure.
type WorkspaceIAMPolicyGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WorkspaceIAMPolicyGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewWorkspaceIAMPolicyGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewWorkspaceIAMPolicyGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewWorkspaceIAMPolicyGetOK creates a WorkspaceIAMPolicyGetOK with default headers values
func NewWorkspaceIAMPolicyGetOK() *WorkspaceIAMPolicyGetOK {
	return &WorkspaceIAMPolicyGetOK{}
}

/*
WorkspaceIAMPolicyGetOK describes a response with status code 200, with default header values.

A successful response.
*/
type WorkspaceIAMPolicyGetOK struct {
	Payload *models.WorkspaceGetWorkspaceIAMPolicyResponse
}

// IsSuccess returns true when this workspace i a m policy get o k response has a 2xx status code
func (o *WorkspaceIAMPolicyGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this workspace i a m policy get o k response has a 3xx status code
func (o *WorkspaceIAMPolicyGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this workspace i a m policy get o k response has a 4xx status code
func (o *WorkspaceIAMPolicyGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this workspace i a m policy get o k response has a 5xx status code
func (o *WorkspaceIAMPolicyGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this workspace i a m policy get o k response a status code equal to that given
func (o *WorkspaceIAMPolicyGetOK) IsCode(code int) bool {
	return code == 200
}

func (o *WorkspaceIAMPolicyGetOK) Error() string {
	return fmt.Sprintf("[GET /v1alpha1/workspaces:iam/{fullName.name}][%d] workspaceIAMPolicyGetOK  %+v", 200, o.Payload)
}

func (o *WorkspaceIAMPolicyGetOK) String() string {
	return fmt.Sprintf("[GET /v1alpha1/workspaces:iam/{fullName.name}][%d] workspaceIAMPolicyGetOK  %+v", 200, o.Payload)
}

func (o *WorkspaceIAMPolicyGetOK) GetPayload() *models.WorkspaceGetWorkspaceIAMPolicyResponse {
	return o.Payload
}

func (o *WorkspaceIAMPolicyGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WorkspaceGetWorkspaceIAMPolicyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewWorkspaceIAMPolicyGetDefault creates a WorkspaceIAMPolicyGetDefault with default headers values
func NewWorkspaceIAMPolicyGetDefault(code int) *WorkspaceIAMPolicyGetDefault {
	return &WorkspaceIAMPolicyGetDefault{
		_statusCode: code,
	}
}

/*
WorkspaceIAMPolicyGetDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type WorkspaceIAMPolicyGetDefault struct {
	_statusCode int

	Payload *models.GrpcGatewayRuntimeError
}

// Code gets the status code for the workspace i a m policy get default response
func (o *WorkspaceIAMPolicyGetDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this workspace i a m policy get default response has a 2xx status code
func (o *WorkspaceIAMPolicyGetDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this workspace i a m policy get default response has a 3xx status code
func (o *WorkspaceIAMPolicyGetDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this workspace i a m policy get default response has a 4xx status code
func (o *WorkspaceIAMPolicyGetDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this workspace i a m policy get default response has a 5xx status code
func (o *WorkspaceIAMPolicyGetDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this workspace i a m policy get default response a status code equal to that given
func (o *WorkspaceIAMPolicyGetDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *WorkspaceIAMPolicyGetDefault) Error() string {
	return fmt.Sprintf("[GET /v1alpha1/workspaces:iam/{fullName.name}][%d] WorkspaceIAMPolicy_Get default  %+v", o._statusCode, o.Payload)
}

func (o *WorkspaceIAMPolicyGetDefault) String() string {
	return fmt.Sprintf("[GET /v1alpha1/workspaces:iam/{fullName.name}][%d] WorkspaceIAMPolicy_Get default  %+v", o._statusCode, o.Payload)
}

func (o *WorkspaceIAMPolicyGetDefault) GetPayload() *models.GrpcGatewayRuntimeError {
	return o.Payload
}

func (o *WorkspaceIAMPolicyGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GrpcGatewayRuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
