// Code generated by go-swagger; DO NOT EDIT.

package provider_aks_cluster_i_a_m_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new provider aks cluster i a m policy API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for provider aks cluster i a m policy API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	ProviderAksClusterIAMPolicyGet(params *ProviderAksClusterIAMPolicyGetParams, opts ...ClientOption) (*ProviderAksClusterIAMPolicyGetOK, error)

	ProviderAksClusterIAMPolicyPatch(params *ProviderAksClusterIAMPolicyPatchParams, opts ...ClientOption) (*ProviderAksClusterIAMPolicyPatchOK, error)

	ProviderAksClusterIAMPolicyTestPermissions(params *ProviderAksClusterIAMPolicyTestPermissionsParams, opts ...ClientOption) (*ProviderAksClusterIAMPolicyTestPermissionsOK, error)

	ProviderAksClusterIAMPolicyUpdate(params *ProviderAksClusterIAMPolicyUpdateParams, opts ...ClientOption) (*ProviderAksClusterIAMPolicyUpdateOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
ProviderAksClusterIAMPolicyGet gets policy for a provider aks cluster
*/
func (a *Client) ProviderAksClusterIAMPolicyGet(params *ProviderAksClusterIAMPolicyGetParams, opts ...ClientOption) (*ProviderAksClusterIAMPolicyGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewProviderAksClusterIAMPolicyGetParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ProviderAksClusterIAMPolicy_Get",
		Method:             "GET",
		PathPattern:        "/v1alpha1/manage/provideraksclusters:iam/{fullName.name}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ProviderAksClusterIAMPolicyGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ProviderAksClusterIAMPolicyGetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ProviderAksClusterIAMPolicyGetDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
ProviderAksClusterIAMPolicyPatch patches a provider aks cluster policy
*/
func (a *Client) ProviderAksClusterIAMPolicyPatch(params *ProviderAksClusterIAMPolicyPatchParams, opts ...ClientOption) (*ProviderAksClusterIAMPolicyPatchOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewProviderAksClusterIAMPolicyPatchParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ProviderAksClusterIAMPolicy_Patch",
		Method:             "PATCH",
		PathPattern:        "/v1alpha1/manage/provideraksclusters:iam/{fullName.name}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ProviderAksClusterIAMPolicyPatchReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ProviderAksClusterIAMPolicyPatchOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ProviderAksClusterIAMPolicyPatchDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
ProviderAksClusterIAMPolicyTestPermissions tests permissions for a provider aks cluster
*/
func (a *Client) ProviderAksClusterIAMPolicyTestPermissions(params *ProviderAksClusterIAMPolicyTestPermissionsParams, opts ...ClientOption) (*ProviderAksClusterIAMPolicyTestPermissionsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewProviderAksClusterIAMPolicyTestPermissionsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ProviderAksClusterIAMPolicy_TestPermissions",
		Method:             "POST",
		PathPattern:        "/v1alpha1/manage/provideraksclusters:iam/{fullName.name}/testPermissions",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ProviderAksClusterIAMPolicyTestPermissionsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ProviderAksClusterIAMPolicyTestPermissionsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ProviderAksClusterIAMPolicyTestPermissionsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
ProviderAksClusterIAMPolicyUpdate updates overwrite policy for a provider aks cluster deleted if body is empty
*/
func (a *Client) ProviderAksClusterIAMPolicyUpdate(params *ProviderAksClusterIAMPolicyUpdateParams, opts ...ClientOption) (*ProviderAksClusterIAMPolicyUpdateOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewProviderAksClusterIAMPolicyUpdateParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ProviderAksClusterIAMPolicy_Update",
		Method:             "PUT",
		PathPattern:        "/v1alpha1/manage/provideraksclusters:iam/{fullName.name}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ProviderAksClusterIAMPolicyUpdateReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ProviderAksClusterIAMPolicyUpdateOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ProviderAksClusterIAMPolicyUpdateDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
