// Code generated by go-swagger; DO NOT EDIT.

package release_resource_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewReleaseResourceServiceGetParams creates a new ReleaseResourceServiceGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewReleaseResourceServiceGetParams() *ReleaseResourceServiceGetParams {
	return &ReleaseResourceServiceGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewReleaseResourceServiceGetParamsWithTimeout creates a new ReleaseResourceServiceGetParams object
// with the ability to set a timeout on a request.
func NewReleaseResourceServiceGetParamsWithTimeout(timeout time.Duration) *ReleaseResourceServiceGetParams {
	return &ReleaseResourceServiceGetParams{
		timeout: timeout,
	}
}

// NewReleaseResourceServiceGetParamsWithContext creates a new ReleaseResourceServiceGetParams object
// with the ability to set a context for a request.
func NewReleaseResourceServiceGetParamsWithContext(ctx context.Context) *ReleaseResourceServiceGetParams {
	return &ReleaseResourceServiceGetParams{
		Context: ctx,
	}
}

// NewReleaseResourceServiceGetParamsWithHTTPClient creates a new ReleaseResourceServiceGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewReleaseResourceServiceGetParamsWithHTTPClient(client *http.Client) *ReleaseResourceServiceGetParams {
	return &ReleaseResourceServiceGetParams{
		HTTPClient: client,
	}
}

/*
ReleaseResourceServiceGetParams contains all the parameters to send to the API endpoint

	for the release resource service get operation.

	Typically these are written to a http.Request.
*/
type ReleaseResourceServiceGetParams struct {

	/* FullNameClusterName.

	   Name of Cluster.
	*/
	FullNameClusterName string

	/* FullNameManagementClusterName.

	   Name of management cluster.
	*/
	FullNameManagementClusterName *string

	/* FullNameName.

	   Name of the Release.
	*/
	FullNameName string

	/* FullNameNamespaceName.

	   Name of Namespace.
	*/
	FullNameNamespaceName string

	/* FullNameOrgID.

	   ID of Organization.
	*/
	FullNameOrgID *string

	/* FullNameProvisionerName.

	   Name of Provisioner.
	*/
	FullNameProvisionerName *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the release resource service get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReleaseResourceServiceGetParams) WithDefaults() *ReleaseResourceServiceGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the release resource service get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReleaseResourceServiceGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the release resource service get params
func (o *ReleaseResourceServiceGetParams) WithTimeout(timeout time.Duration) *ReleaseResourceServiceGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the release resource service get params
func (o *ReleaseResourceServiceGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the release resource service get params
func (o *ReleaseResourceServiceGetParams) WithContext(ctx context.Context) *ReleaseResourceServiceGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the release resource service get params
func (o *ReleaseResourceServiceGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the release resource service get params
func (o *ReleaseResourceServiceGetParams) WithHTTPClient(client *http.Client) *ReleaseResourceServiceGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the release resource service get params
func (o *ReleaseResourceServiceGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFullNameClusterName adds the fullNameClusterName to the release resource service get params
func (o *ReleaseResourceServiceGetParams) WithFullNameClusterName(fullNameClusterName string) *ReleaseResourceServiceGetParams {
	o.SetFullNameClusterName(fullNameClusterName)
	return o
}

// SetFullNameClusterName adds the fullNameClusterName to the release resource service get params
func (o *ReleaseResourceServiceGetParams) SetFullNameClusterName(fullNameClusterName string) {
	o.FullNameClusterName = fullNameClusterName
}

// WithFullNameManagementClusterName adds the fullNameManagementClusterName to the release resource service get params
func (o *ReleaseResourceServiceGetParams) WithFullNameManagementClusterName(fullNameManagementClusterName *string) *ReleaseResourceServiceGetParams {
	o.SetFullNameManagementClusterName(fullNameManagementClusterName)
	return o
}

// SetFullNameManagementClusterName adds the fullNameManagementClusterName to the release resource service get params
func (o *ReleaseResourceServiceGetParams) SetFullNameManagementClusterName(fullNameManagementClusterName *string) {
	o.FullNameManagementClusterName = fullNameManagementClusterName
}

// WithFullNameName adds the fullNameName to the release resource service get params
func (o *ReleaseResourceServiceGetParams) WithFullNameName(fullNameName string) *ReleaseResourceServiceGetParams {
	o.SetFullNameName(fullNameName)
	return o
}

// SetFullNameName adds the fullNameName to the release resource service get params
func (o *ReleaseResourceServiceGetParams) SetFullNameName(fullNameName string) {
	o.FullNameName = fullNameName
}

// WithFullNameNamespaceName adds the fullNameNamespaceName to the release resource service get params
func (o *ReleaseResourceServiceGetParams) WithFullNameNamespaceName(fullNameNamespaceName string) *ReleaseResourceServiceGetParams {
	o.SetFullNameNamespaceName(fullNameNamespaceName)
	return o
}

// SetFullNameNamespaceName adds the fullNameNamespaceName to the release resource service get params
func (o *ReleaseResourceServiceGetParams) SetFullNameNamespaceName(fullNameNamespaceName string) {
	o.FullNameNamespaceName = fullNameNamespaceName
}

// WithFullNameOrgID adds the fullNameOrgID to the release resource service get params
func (o *ReleaseResourceServiceGetParams) WithFullNameOrgID(fullNameOrgID *string) *ReleaseResourceServiceGetParams {
	o.SetFullNameOrgID(fullNameOrgID)
	return o
}

// SetFullNameOrgID adds the fullNameOrgId to the release resource service get params
func (o *ReleaseResourceServiceGetParams) SetFullNameOrgID(fullNameOrgID *string) {
	o.FullNameOrgID = fullNameOrgID
}

// WithFullNameProvisionerName adds the fullNameProvisionerName to the release resource service get params
func (o *ReleaseResourceServiceGetParams) WithFullNameProvisionerName(fullNameProvisionerName *string) *ReleaseResourceServiceGetParams {
	o.SetFullNameProvisionerName(fullNameProvisionerName)
	return o
}

// SetFullNameProvisionerName adds the fullNameProvisionerName to the release resource service get params
func (o *ReleaseResourceServiceGetParams) SetFullNameProvisionerName(fullNameProvisionerName *string) {
	o.FullNameProvisionerName = fullNameProvisionerName
}

// WriteToRequest writes these params to a swagger request
func (o *ReleaseResourceServiceGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param fullName.clusterName
	if err := r.SetPathParam("fullName.clusterName", o.FullNameClusterName); err != nil {
		return err
	}

	if o.FullNameManagementClusterName != nil {

		// query param fullName.managementClusterName
		var qrFullNameManagementClusterName string

		if o.FullNameManagementClusterName != nil {
			qrFullNameManagementClusterName = *o.FullNameManagementClusterName
		}
		qFullNameManagementClusterName := qrFullNameManagementClusterName
		if qFullNameManagementClusterName != "" {

			if err := r.SetQueryParam("fullName.managementClusterName", qFullNameManagementClusterName); err != nil {
				return err
			}
		}
	}

	// path param fullName.name
	if err := r.SetPathParam("fullName.name", o.FullNameName); err != nil {
		return err
	}

	// path param fullName.namespaceName
	if err := r.SetPathParam("fullName.namespaceName", o.FullNameNamespaceName); err != nil {
		return err
	}

	if o.FullNameOrgID != nil {

		// query param fullName.orgId
		var qrFullNameOrgID string

		if o.FullNameOrgID != nil {
			qrFullNameOrgID = *o.FullNameOrgID
		}
		qFullNameOrgID := qrFullNameOrgID
		if qFullNameOrgID != "" {

			if err := r.SetQueryParam("fullName.orgId", qFullNameOrgID); err != nil {
				return err
			}
		}
	}

	if o.FullNameProvisionerName != nil {

		// query param fullName.provisionerName
		var qrFullNameProvisionerName string

		if o.FullNameProvisionerName != nil {
			qrFullNameProvisionerName = *o.FullNameProvisionerName
		}
		qFullNameProvisionerName := qrFullNameProvisionerName
		if qFullNameProvisionerName != "" {

			if err := r.SetQueryParam("fullName.provisionerName", qFullNameProvisionerName); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
