// Code generated by go-swagger; DO NOT EDIT.

package binaries_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new binaries service API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for binaries service API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	BinariesServiceGet(params *BinariesServiceGetParams, opts ...ClientOption) (*BinariesServiceGetOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
BinariesServiceGet requests to get the links to the latest c l i binaries
*/
func (a *Client) BinariesServiceGet(params *BinariesServiceGetParams, opts ...ClientOption) (*BinariesServiceGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewBinariesServiceGetParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "BinariesService_Get",
		Method:             "GET",
		PathPattern:        "/v1alpha1/system/binaries",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &BinariesServiceGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*BinariesServiceGetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*BinariesServiceGetDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
