// Code generated by go-swagger; DO NOT EDIT.

package audit_resource_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/warroyo/tmc-go-rest-sdk/models"
)

// AuditResourceServiceListReader is a Reader for the AuditResourceServiceList structure.
type AuditResourceServiceListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AuditResourceServiceListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAuditResourceServiceListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewAuditResourceServiceListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAuditResourceServiceListOK creates a AuditResourceServiceListOK with default headers values
func NewAuditResourceServiceListOK() *AuditResourceServiceListOK {
	return &AuditResourceServiceListOK{}
}

/*
AuditResourceServiceListOK describes a response with status code 200, with default header values.

A successful response.
*/
type AuditResourceServiceListOK struct {
	Payload *models.AuditListAuditsResponse
}

// IsSuccess returns true when this audit resource service list o k response has a 2xx status code
func (o *AuditResourceServiceListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this audit resource service list o k response has a 3xx status code
func (o *AuditResourceServiceListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this audit resource service list o k response has a 4xx status code
func (o *AuditResourceServiceListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this audit resource service list o k response has a 5xx status code
func (o *AuditResourceServiceListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this audit resource service list o k response a status code equal to that given
func (o *AuditResourceServiceListOK) IsCode(code int) bool {
	return code == 200
}

func (o *AuditResourceServiceListOK) Error() string {
	return fmt.Sprintf("[GET /v1alpha1/audits][%d] auditResourceServiceListOK  %+v", 200, o.Payload)
}

func (o *AuditResourceServiceListOK) String() string {
	return fmt.Sprintf("[GET /v1alpha1/audits][%d] auditResourceServiceListOK  %+v", 200, o.Payload)
}

func (o *AuditResourceServiceListOK) GetPayload() *models.AuditListAuditsResponse {
	return o.Payload
}

func (o *AuditResourceServiceListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuditListAuditsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAuditResourceServiceListDefault creates a AuditResourceServiceListDefault with default headers values
func NewAuditResourceServiceListDefault(code int) *AuditResourceServiceListDefault {
	return &AuditResourceServiceListDefault{
		_statusCode: code,
	}
}

/*
AuditResourceServiceListDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type AuditResourceServiceListDefault struct {
	_statusCode int

	Payload *models.GrpcGatewayRuntimeError
}

// Code gets the status code for the audit resource service list default response
func (o *AuditResourceServiceListDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this audit resource service list default response has a 2xx status code
func (o *AuditResourceServiceListDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this audit resource service list default response has a 3xx status code
func (o *AuditResourceServiceListDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this audit resource service list default response has a 4xx status code
func (o *AuditResourceServiceListDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this audit resource service list default response has a 5xx status code
func (o *AuditResourceServiceListDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this audit resource service list default response a status code equal to that given
func (o *AuditResourceServiceListDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *AuditResourceServiceListDefault) Error() string {
	return fmt.Sprintf("[GET /v1alpha1/audits][%d] AuditResourceService_List default  %+v", o._statusCode, o.Payload)
}

func (o *AuditResourceServiceListDefault) String() string {
	return fmt.Sprintf("[GET /v1alpha1/audits][%d] AuditResourceService_List default  %+v", o._statusCode, o.Payload)
}

func (o *AuditResourceServiceListDefault) GetPayload() *models.GrpcGatewayRuntimeError {
	return o.Payload
}

func (o *AuditResourceServiceListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GrpcGatewayRuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
