// Code generated by go-swagger; DO NOT EDIT.

package git_repository_resource_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/warroyo/tmc-go-rest-sdk/models"
)

// GitRepositoryResourceServiceCreateReader is a Reader for the GitRepositoryResourceServiceCreate structure.
type GitRepositoryResourceServiceCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GitRepositoryResourceServiceCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGitRepositoryResourceServiceCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGitRepositoryResourceServiceCreateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGitRepositoryResourceServiceCreateOK creates a GitRepositoryResourceServiceCreateOK with default headers values
func NewGitRepositoryResourceServiceCreateOK() *GitRepositoryResourceServiceCreateOK {
	return &GitRepositoryResourceServiceCreateOK{}
}

/*
GitRepositoryResourceServiceCreateOK describes a response with status code 200, with default header values.

A successful response.
*/
type GitRepositoryResourceServiceCreateOK struct {
	Payload *models.ClusterNamespaceFluxcdGitrepositoryCreateGitRepositoryResponse
}

// IsSuccess returns true when this git repository resource service create o k response has a 2xx status code
func (o *GitRepositoryResourceServiceCreateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this git repository resource service create o k response has a 3xx status code
func (o *GitRepositoryResourceServiceCreateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this git repository resource service create o k response has a 4xx status code
func (o *GitRepositoryResourceServiceCreateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this git repository resource service create o k response has a 5xx status code
func (o *GitRepositoryResourceServiceCreateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this git repository resource service create o k response a status code equal to that given
func (o *GitRepositoryResourceServiceCreateOK) IsCode(code int) bool {
	return code == 200
}

func (o *GitRepositoryResourceServiceCreateOK) Error() string {
	return fmt.Sprintf("[POST /v1alpha1/clusters/{gitRepository.fullName.clusterName}/namespaces/{gitRepository.fullName.namespaceName}/fluxcd/gitrepositories][%d] gitRepositoryResourceServiceCreateOK  %+v", 200, o.Payload)
}

func (o *GitRepositoryResourceServiceCreateOK) String() string {
	return fmt.Sprintf("[POST /v1alpha1/clusters/{gitRepository.fullName.clusterName}/namespaces/{gitRepository.fullName.namespaceName}/fluxcd/gitrepositories][%d] gitRepositoryResourceServiceCreateOK  %+v", 200, o.Payload)
}

func (o *GitRepositoryResourceServiceCreateOK) GetPayload() *models.ClusterNamespaceFluxcdGitrepositoryCreateGitRepositoryResponse {
	return o.Payload
}

func (o *GitRepositoryResourceServiceCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ClusterNamespaceFluxcdGitrepositoryCreateGitRepositoryResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGitRepositoryResourceServiceCreateDefault creates a GitRepositoryResourceServiceCreateDefault with default headers values
func NewGitRepositoryResourceServiceCreateDefault(code int) *GitRepositoryResourceServiceCreateDefault {
	return &GitRepositoryResourceServiceCreateDefault{
		_statusCode: code,
	}
}

/*
GitRepositoryResourceServiceCreateDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type GitRepositoryResourceServiceCreateDefault struct {
	_statusCode int

	Payload *models.GrpcGatewayRuntimeError
}

// Code gets the status code for the git repository resource service create default response
func (o *GitRepositoryResourceServiceCreateDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this git repository resource service create default response has a 2xx status code
func (o *GitRepositoryResourceServiceCreateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this git repository resource service create default response has a 3xx status code
func (o *GitRepositoryResourceServiceCreateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this git repository resource service create default response has a 4xx status code
func (o *GitRepositoryResourceServiceCreateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this git repository resource service create default response has a 5xx status code
func (o *GitRepositoryResourceServiceCreateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this git repository resource service create default response a status code equal to that given
func (o *GitRepositoryResourceServiceCreateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *GitRepositoryResourceServiceCreateDefault) Error() string {
	return fmt.Sprintf("[POST /v1alpha1/clusters/{gitRepository.fullName.clusterName}/namespaces/{gitRepository.fullName.namespaceName}/fluxcd/gitrepositories][%d] GitRepositoryResourceService_Create default  %+v", o._statusCode, o.Payload)
}

func (o *GitRepositoryResourceServiceCreateDefault) String() string {
	return fmt.Sprintf("[POST /v1alpha1/clusters/{gitRepository.fullName.clusterName}/namespaces/{gitRepository.fullName.namespaceName}/fluxcd/gitrepositories][%d] GitRepositoryResourceService_Create default  %+v", o._statusCode, o.Payload)
}

func (o *GitRepositoryResourceServiceCreateDefault) GetPayload() *models.GrpcGatewayRuntimeError {
	return o.Payload
}

func (o *GitRepositoryResourceServiceCreateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GrpcGatewayRuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
