// Code generated by go-swagger; DO NOT EDIT.

package recipe_resource_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/warroyo/tmc-go-rest-sdk/models"
)

// RecipeResourceServiceGetReader is a Reader for the RecipeResourceServiceGet structure.
type RecipeResourceServiceGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RecipeResourceServiceGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRecipeResourceServiceGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRecipeResourceServiceGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRecipeResourceServiceGetOK creates a RecipeResourceServiceGetOK with default headers values
func NewRecipeResourceServiceGetOK() *RecipeResourceServiceGetOK {
	return &RecipeResourceServiceGetOK{}
}

/*
RecipeResourceServiceGetOK describes a response with status code 200, with default header values.

A successful response.
*/
type RecipeResourceServiceGetOK struct {
	Payload *models.PolicyTypeRecipeGetRecipeResponse
}

// IsSuccess returns true when this recipe resource service get o k response has a 2xx status code
func (o *RecipeResourceServiceGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this recipe resource service get o k response has a 3xx status code
func (o *RecipeResourceServiceGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this recipe resource service get o k response has a 4xx status code
func (o *RecipeResourceServiceGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this recipe resource service get o k response has a 5xx status code
func (o *RecipeResourceServiceGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this recipe resource service get o k response a status code equal to that given
func (o *RecipeResourceServiceGetOK) IsCode(code int) bool {
	return code == 200
}

func (o *RecipeResourceServiceGetOK) Error() string {
	return fmt.Sprintf("[GET /v1alpha1/policy/types/{fullName.typeName}/recipes/{fullName.name}][%d] recipeResourceServiceGetOK  %+v", 200, o.Payload)
}

func (o *RecipeResourceServiceGetOK) String() string {
	return fmt.Sprintf("[GET /v1alpha1/policy/types/{fullName.typeName}/recipes/{fullName.name}][%d] recipeResourceServiceGetOK  %+v", 200, o.Payload)
}

func (o *RecipeResourceServiceGetOK) GetPayload() *models.PolicyTypeRecipeGetRecipeResponse {
	return o.Payload
}

func (o *RecipeResourceServiceGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PolicyTypeRecipeGetRecipeResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRecipeResourceServiceGetDefault creates a RecipeResourceServiceGetDefault with default headers values
func NewRecipeResourceServiceGetDefault(code int) *RecipeResourceServiceGetDefault {
	return &RecipeResourceServiceGetDefault{
		_statusCode: code,
	}
}

/*
RecipeResourceServiceGetDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type RecipeResourceServiceGetDefault struct {
	_statusCode int

	Payload *models.GrpcGatewayRuntimeError
}

// Code gets the status code for the recipe resource service get default response
func (o *RecipeResourceServiceGetDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this recipe resource service get default response has a 2xx status code
func (o *RecipeResourceServiceGetDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this recipe resource service get default response has a 3xx status code
func (o *RecipeResourceServiceGetDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this recipe resource service get default response has a 4xx status code
func (o *RecipeResourceServiceGetDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this recipe resource service get default response has a 5xx status code
func (o *RecipeResourceServiceGetDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this recipe resource service get default response a status code equal to that given
func (o *RecipeResourceServiceGetDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *RecipeResourceServiceGetDefault) Error() string {
	return fmt.Sprintf("[GET /v1alpha1/policy/types/{fullName.typeName}/recipes/{fullName.name}][%d] RecipeResourceService_Get default  %+v", o._statusCode, o.Payload)
}

func (o *RecipeResourceServiceGetDefault) String() string {
	return fmt.Sprintf("[GET /v1alpha1/policy/types/{fullName.typeName}/recipes/{fullName.name}][%d] RecipeResourceService_Get default  %+v", o._statusCode, o.Payload)
}

func (o *RecipeResourceServiceGetDefault) GetPayload() *models.GrpcGatewayRuntimeError {
	return o.Payload
}

func (o *RecipeResourceServiceGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GrpcGatewayRuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
