// Code generated by go-swagger; DO NOT EDIT.

package data_protection_resource_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/warroyo/tmc-go-rest-sdk/models"
)

// DataProtectionResourceServiceCreateReader is a Reader for the DataProtectionResourceServiceCreate structure.
type DataProtectionResourceServiceCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DataProtectionResourceServiceCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDataProtectionResourceServiceCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDataProtectionResourceServiceCreateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDataProtectionResourceServiceCreateOK creates a DataProtectionResourceServiceCreateOK with default headers values
func NewDataProtectionResourceServiceCreateOK() *DataProtectionResourceServiceCreateOK {
	return &DataProtectionResourceServiceCreateOK{}
}

/*
DataProtectionResourceServiceCreateOK describes a response with status code 200, with default header values.

A successful response.
*/
type DataProtectionResourceServiceCreateOK struct {
	Payload *models.ClusterDataprotectionCreateDataProtectionResponse
}

// IsSuccess returns true when this data protection resource service create o k response has a 2xx status code
func (o *DataProtectionResourceServiceCreateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this data protection resource service create o k response has a 3xx status code
func (o *DataProtectionResourceServiceCreateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this data protection resource service create o k response has a 4xx status code
func (o *DataProtectionResourceServiceCreateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this data protection resource service create o k response has a 5xx status code
func (o *DataProtectionResourceServiceCreateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this data protection resource service create o k response a status code equal to that given
func (o *DataProtectionResourceServiceCreateOK) IsCode(code int) bool {
	return code == 200
}

func (o *DataProtectionResourceServiceCreateOK) Error() string {
	return fmt.Sprintf("[POST /v1alpha1/clusters/{dataProtection.fullName.clusterName}/dataprotection][%d] dataProtectionResourceServiceCreateOK  %+v", 200, o.Payload)
}

func (o *DataProtectionResourceServiceCreateOK) String() string {
	return fmt.Sprintf("[POST /v1alpha1/clusters/{dataProtection.fullName.clusterName}/dataprotection][%d] dataProtectionResourceServiceCreateOK  %+v", 200, o.Payload)
}

func (o *DataProtectionResourceServiceCreateOK) GetPayload() *models.ClusterDataprotectionCreateDataProtectionResponse {
	return o.Payload
}

func (o *DataProtectionResourceServiceCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ClusterDataprotectionCreateDataProtectionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDataProtectionResourceServiceCreateDefault creates a DataProtectionResourceServiceCreateDefault with default headers values
func NewDataProtectionResourceServiceCreateDefault(code int) *DataProtectionResourceServiceCreateDefault {
	return &DataProtectionResourceServiceCreateDefault{
		_statusCode: code,
	}
}

/*
DataProtectionResourceServiceCreateDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type DataProtectionResourceServiceCreateDefault struct {
	_statusCode int

	Payload *models.GrpcGatewayRuntimeError
}

// Code gets the status code for the data protection resource service create default response
func (o *DataProtectionResourceServiceCreateDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this data protection resource service create default response has a 2xx status code
func (o *DataProtectionResourceServiceCreateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this data protection resource service create default response has a 3xx status code
func (o *DataProtectionResourceServiceCreateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this data protection resource service create default response has a 4xx status code
func (o *DataProtectionResourceServiceCreateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this data protection resource service create default response has a 5xx status code
func (o *DataProtectionResourceServiceCreateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this data protection resource service create default response a status code equal to that given
func (o *DataProtectionResourceServiceCreateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *DataProtectionResourceServiceCreateDefault) Error() string {
	return fmt.Sprintf("[POST /v1alpha1/clusters/{dataProtection.fullName.clusterName}/dataprotection][%d] DataProtectionResourceService_Create default  %+v", o._statusCode, o.Payload)
}

func (o *DataProtectionResourceServiceCreateDefault) String() string {
	return fmt.Sprintf("[POST /v1alpha1/clusters/{dataProtection.fullName.clusterName}/dataprotection][%d] DataProtectionResourceService_Create default  %+v", o._statusCode, o.Payload)
}

func (o *DataProtectionResourceServiceCreateDefault) GetPayload() *models.GrpcGatewayRuntimeError {
	return o.Payload
}

func (o *DataProtectionResourceServiceCreateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GrpcGatewayRuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
