// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// AccountCredentialProvider Provider definition - indicates the credential provider.
//
//   - PROVIDER_UNSPECIFIED: Unspecified credential provider (default).
//   - AWS_EC2: AmazonWeb Services EC2.
//   - GENERIC_S3: Generic S3 provider.
//   - AZURE_AD: Azure Active Directory.
//   - AWS_EKS: AWS EKS.
//   - AZURE_AKS: Azure AKS.
//   - GENERIC_KEY_VALUE: Generic key value pair.
//
// swagger:model account.credential.Provider
type AccountCredentialProvider string

func NewAccountCredentialProvider(value AccountCredentialProvider) *AccountCredentialProvider {
	return &value
}

// Pointer returns a pointer to a freshly-allocated AccountCredentialProvider.
func (m AccountCredentialProvider) Pointer() *AccountCredentialProvider {
	return &m
}

const (

	// AccountCredentialProviderPROVIDERUNSPECIFIED captures enum value "PROVIDER_UNSPECIFIED"
	AccountCredentialProviderPROVIDERUNSPECIFIED AccountCredentialProvider = "PROVIDER_UNSPECIFIED"

	// AccountCredentialProviderAWSEC2 captures enum value "AWS_EC2"
	AccountCredentialProviderAWSEC2 AccountCredentialProvider = "AWS_EC2"

	// AccountCredentialProviderGENERICS3 captures enum value "GENERIC_S3"
	AccountCredentialProviderGENERICS3 AccountCredentialProvider = "GENERIC_S3"

	// AccountCredentialProviderAZUREAD captures enum value "AZURE_AD"
	AccountCredentialProviderAZUREAD AccountCredentialProvider = "AZURE_AD"

	// AccountCredentialProviderAWSEKS captures enum value "AWS_EKS"
	AccountCredentialProviderAWSEKS AccountCredentialProvider = "AWS_EKS"

	// AccountCredentialProviderAZUREAKS captures enum value "AZURE_AKS"
	AccountCredentialProviderAZUREAKS AccountCredentialProvider = "AZURE_AKS"

	// AccountCredentialProviderGENERICKEYVALUE captures enum value "GENERIC_KEY_VALUE"
	AccountCredentialProviderGENERICKEYVALUE AccountCredentialProvider = "GENERIC_KEY_VALUE"
)

// for schema
var accountCredentialProviderEnum []interface{}

func init() {
	var res []AccountCredentialProvider
	if err := json.Unmarshal([]byte(`["PROVIDER_UNSPECIFIED","AWS_EC2","GENERIC_S3","AZURE_AD","AWS_EKS","AZURE_AKS","GENERIC_KEY_VALUE"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		accountCredentialProviderEnum = append(accountCredentialProviderEnum, v)
	}
}

func (m AccountCredentialProvider) validateAccountCredentialProviderEnum(path, location string, value AccountCredentialProvider) error {
	if err := validate.EnumCase(path, location, value, accountCredentialProviderEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this account credential provider
func (m AccountCredentialProvider) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateAccountCredentialProviderEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this account credential provider based on context it is used
func (m AccountCredentialProvider) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
