// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AksclusterMonitoringAddonConfig The monitoring addon config.
//
// swagger:model akscluster.MonitoringAddonConfig
type AksclusterMonitoringAddonConfig struct {

	// Whether the monitoring addon is enabled or not.
	Enabled bool `json:"enabled,omitempty"`

	// The log analytics workspace id for the monitoring addon.
	LogAnalyticsWorkspaceID string `json:"logAnalyticsWorkspaceId,omitempty"`
}

// Validate validates this akscluster monitoring addon config
func (m *AksclusterMonitoringAddonConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this akscluster monitoring addon config based on context it is used
func (m *AksclusterMonitoringAddonConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AksclusterMonitoringAddonConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AksclusterMonitoringAddonConfig) UnmarshalBinary(b []byte) error {
	var res AksclusterMonitoringAddonConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
