// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ClusterDataprotectionScheduleDeleteScheduleResponse Response from deleting a Schedule.
//
// swagger:model cluster.dataprotection.schedule.DeleteScheduleResponse
type ClusterDataprotectionScheduleDeleteScheduleResponse struct {

	// Message regarding deletion.
	Message string `json:"message,omitempty"`
}

// Validate validates this cluster dataprotection schedule delete schedule response
func (m *ClusterDataprotectionScheduleDeleteScheduleResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this cluster dataprotection schedule delete schedule response based on context it is used
func (m *ClusterDataprotectionScheduleDeleteScheduleResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ClusterDataprotectionScheduleDeleteScheduleResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClusterDataprotectionScheduleDeleteScheduleResponse) UnmarshalBinary(b []byte) error {
	var res ClusterDataprotectionScheduleDeleteScheduleResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
