// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ClusterInfrastructureTkgawsSubnet Subnet configuration for the cluster.
//
// swagger:model cluster.infrastructure.tkgaws.Subnet
type ClusterInfrastructureTkgawsSubnet struct {

	// AWS availability zone e.g. us-west-2a
	AvailabilityZone string `json:"availabilityZone,omitempty"`

	// CIDR for AWS subnet.
	// This CIDR block must be in the range of AWS VPC CIDR block.
	CidrBlock string `json:"cidrBlock,omitempty"`

	// AWS subnet ID. The rest of the fields are ignored if this field is specified.
	ID string `json:"id,omitempty"`

	// Public subnet or private subnet.
	IsPublic bool `json:"isPublic,omitempty"`
}

// Validate validates this cluster infrastructure tkgaws subnet
func (m *ClusterInfrastructureTkgawsSubnet) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this cluster infrastructure tkgaws subnet based on context it is used
func (m *ClusterInfrastructureTkgawsSubnet) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ClusterInfrastructureTkgawsSubnet) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClusterInfrastructureTkgawsSubnet) UnmarshalBinary(b []byte) error {
	var res ClusterInfrastructureTkgawsSubnet
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
