// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ClustergroupFullName Full name of the cluster group. This includes the object name along
// with any parents or further identifiers.
//
// swagger:model clustergroup.FullName
type ClustergroupFullName struct {

	// Name of this ClusterGroup.
	Name string `json:"name,omitempty"`

	// ID of Organization.
	OrgID string `json:"orgId,omitempty"`
}

// Validate validates this clustergroup full name
func (m *ClustergroupFullName) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this clustergroup full name based on context it is used
func (m *ClustergroupFullName) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ClustergroupFullName) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClustergroupFullName) UnmarshalBinary(b []byte) error {
	var res ClustergroupFullName
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
