// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EksclusterImageOptions Available image options.
//
// swagger:model ekscluster.ImageOptions
type EksclusterImageOptions struct {

	// Architecture type.
	ArchitectureType string `json:"architectureType,omitempty"`

	// Image id.
	ImageID string `json:"imageId,omitempty"`

	// Image name.
	ImageName string `json:"imageName,omitempty"`

	// Root disk size.
	RootDiskSize int32 `json:"rootDiskSize,omitempty"`

	// Root disk type.
	RootDiskType string `json:"rootDiskType,omitempty"`
}

// Validate validates this ekscluster image options
func (m *EksclusterImageOptions) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this ekscluster image options based on context it is used
func (m *EksclusterImageOptions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EksclusterImageOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EksclusterImageOptions) UnmarshalBinary(b []byte) error {
	var res EksclusterImageOptions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
