// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ManagementclusterProvisionerClusterclassStatus Status of the cluster class.
//
// swagger:model managementcluster.provisioner.clusterclass.Status
type ManagementclusterProvisionerClusterclassStatus struct {

	// Conditions of the resource.
	Conditions map[string]VmwareTanzuCoreV1alpha1StatusCondition `json:"conditions,omitempty"`

	// Schema of cluster class variables for UI to render.
	VariablesSchema *K8sIoApimachineryPkgRuntimeRawExtension `json:"variablesSchema,omitempty"`
}

// Validate validates this managementcluster provisioner clusterclass status
func (m *ManagementclusterProvisionerClusterclassStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConditions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVariablesSchema(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ManagementclusterProvisionerClusterclassStatus) validateConditions(formats strfmt.Registry) error {
	if swag.IsZero(m.Conditions) { // not required
		return nil
	}

	for k := range m.Conditions {

		if err := validate.Required("conditions"+"."+k, "body", m.Conditions[k]); err != nil {
			return err
		}
		if val, ok := m.Conditions[k]; ok {
			if err := val.Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("conditions" + "." + k)
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("conditions" + "." + k)
				}
				return err
			}
		}

	}

	return nil
}

func (m *ManagementclusterProvisionerClusterclassStatus) validateVariablesSchema(formats strfmt.Registry) error {
	if swag.IsZero(m.VariablesSchema) { // not required
		return nil
	}

	if m.VariablesSchema != nil {
		if err := m.VariablesSchema.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("variablesSchema")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("variablesSchema")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this managementcluster provisioner clusterclass status based on the context it is used
func (m *ManagementclusterProvisionerClusterclassStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateConditions(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateVariablesSchema(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ManagementclusterProvisionerClusterclassStatus) contextValidateConditions(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.Conditions {

		if val, ok := m.Conditions[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

func (m *ManagementclusterProvisionerClusterclassStatus) contextValidateVariablesSchema(ctx context.Context, formats strfmt.Registry) error {

	if m.VariablesSchema != nil {
		if err := m.VariablesSchema.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("variablesSchema")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("variablesSchema")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ManagementclusterProvisionerClusterclassStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ManagementclusterProvisionerClusterclassStatus) UnmarshalBinary(b []byte) error {
	var res ManagementclusterProvisionerClusterclassStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
