// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ManagementclusterProvisionerCreateProvisionerResponse Response from creating a Provisioner.
//
// swagger:model managementcluster.provisioner.CreateProvisionerResponse
type ManagementclusterProvisionerCreateProvisionerResponse struct {

	// Provisioner created.
	Provisioner *ManagementclusterProvisionerProvisioner `json:"provisioner,omitempty"`
}

// Validate validates this managementcluster provisioner create provisioner response
func (m *ManagementclusterProvisionerCreateProvisionerResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProvisioner(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ManagementclusterProvisionerCreateProvisionerResponse) validateProvisioner(formats strfmt.Registry) error {
	if swag.IsZero(m.Provisioner) { // not required
		return nil
	}

	if m.Provisioner != nil {
		if err := m.Provisioner.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("provisioner")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("provisioner")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this managementcluster provisioner create provisioner response based on the context it is used
func (m *ManagementclusterProvisionerCreateProvisionerResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateProvisioner(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ManagementclusterProvisionerCreateProvisionerResponse) contextValidateProvisioner(ctx context.Context, formats strfmt.Registry) error {

	if m.Provisioner != nil {
		if err := m.Provisioner.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("provisioner")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("provisioner")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ManagementclusterProvisionerCreateProvisionerResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ManagementclusterProvisionerCreateProvisionerResponse) UnmarshalBinary(b []byte) error {
	var res ManagementclusterProvisionerCreateProvisionerResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
