// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PolicyTypeRecipeVersionSearchScope Scope to search by, any fields left empty will be considered all (*).
//
// swagger:model policy.type.recipe.version.SearchScope
type PolicyTypeRecipeVersionSearchScope struct {

	// Scope search to the specified name; supports globbing; default (*).
	Name string `json:"name,omitempty"`

	// Scope search to the specified recipe_name; supports globbing; default (*).
	RecipeName string `json:"recipeName,omitempty"`

	// Scope search to the specified type_name; supports globbing; default (*).
	TypeName string `json:"typeName,omitempty"`
}

// Validate validates this policy type recipe version search scope
func (m *PolicyTypeRecipeVersionSearchScope) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this policy type recipe version search scope based on context it is used
func (m *PolicyTypeRecipeVersionSearchScope) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PolicyTypeRecipeVersionSearchScope) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PolicyTypeRecipeVersionSearchScope) UnmarshalBinary(b []byte) error {
	var res PolicyTypeRecipeVersionSearchScope
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
