// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SettingEffectiveSearchScope Scope to search by, any fields left empty will be considered all (*).
//
// swagger:model setting.effective.SearchScope
type SettingEffectiveSearchScope struct {

	// Scope search to the specified name; supports globbing; default (*).
	Name string `json:"name,omitempty"`

	// Filter by type of setting; supports globbing; default (*).
	SettingType string `json:"settingType,omitempty"`

	// Filter by RID of target resource; supports globbing; default (*).
	TargetResourceRid string `json:"targetResourceRid,omitempty"`

	// Filter by UID of target resource; supports globbing; default (*).
	TargetResourceUID string `json:"targetResourceUid,omitempty"`
}

// Validate validates this setting effective search scope
func (m *SettingEffectiveSearchScope) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this setting effective search scope based on context it is used
func (m *SettingEffectiveSearchScope) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SettingEffectiveSearchScope) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SettingEffectiveSearchScope) UnmarshalBinary(b []byte) error {
	var res SettingEffectiveSearchScope
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
