// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TanzupackageTapSolutionDeleteSolutionResponse Response from deleting a Solution.
//
// swagger:model tanzupackage.tap.solution.DeleteSolutionResponse
type TanzupackageTapSolutionDeleteSolutionResponse struct {

	// Message regarding deletion.
	Message string `json:"message,omitempty"`
}

// Validate validates this tanzupackage tap solution delete solution response
func (m *TanzupackageTapSolutionDeleteSolutionResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this tanzupackage tap solution delete solution response based on context it is used
func (m *TanzupackageTapSolutionDeleteSolutionResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TanzupackageTapSolutionDeleteSolutionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TanzupackageTapSolutionDeleteSolutionResponse) UnmarshalBinary(b []byte) error {
	var res TanzupackageTapSolutionDeleteSolutionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
